### ISSUE TITLE
Add Patient Search to People Tab

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1022]
Problem: Finding Patients at facilities with hundreds of users can be challenging and time consuming

Solution: Add "Filter" Button and only search bar so Users can search for Patient names Benefit: Users can more easily find a person to edit and don't need to load all people to do so)

On key entry in the search the people table should update to reflect the people returned by quering `patients` and `patientsCount` and including the search temr

![Screen Shot 2021-03-10 at 3 35 11 PM](https://user-images.githubusercontent.com/80347105/110694131-41a07d80-81b6-11eb-9039-47f8ed479ee3.png)

**Comment by timbest-usds** [comment]
The backend work is done to filter patients list based on a search string (see #1019)

The patient search box in the Add to Queue tab is wired up to use the new api.

The next step is to use it in the Patients List tab. See #740 for UI and notes.

**Comment by nickscialli-usds** [comment]
My assumption here is that we're going to send the user back to page 1 whenever the search is executed, regardless of the current search page. Not sure how this could work otherwise.

**Comment by nickscialli-usds** [comment]
@katiealoisi @hmyers-cms Quick UX question here: let's say I have a filter in progress. Should I be able to close the filter menu (or whatever we call the gray area) by re-clicking the "Filter" button? I think that might be confusing if I could close the filter menu since I wouldn't know what filters I currently have on. Maybe we could make that "Filters" button disappear when you click it an add a new button on the right side of the gray area that says "Clear Filters"?

**Comment by nickscialli-usds** [comment]
Also, what is the purpose of the search button (the magnifying glass)? If our search is a debounced typeahead, the search button seems to basically offers no additional functionality.

**Comment by hmyers-cms** [comment]
Okay talked w/ @katiealoisi and we agree the best option is to make the filters clear when you click the button to close the drawer. When the drawer is open, the button text can change to say "Clear filters". This is reflected in the eng-ready prototype now
