### ISSUE TITLE
Update CSV Schema to add Patient Preferred Language and Tribal Affiliation

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1239]

**Comment by katiealoisi** [comment]
Can we label the field "Primary language" instead of "Patient preferred language"? @aliciabeckett-gov 
Preferred language and primary language are not necessarily the same thing; Asking for preferred language may lead to higher (maybe artificial) demand for translators and slow down case investigation when it's not really necessary.
