### ISSUE TITLE
Verify user email on signup

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1263]
When the user submits a request to `/account-request` there is no verification on the contact information that is sent to the user. This is a potential area for user drop off as they might submit a request and leave us with no way of contacting them.

On submit of the signup form. Users should be prompted to check their email for next steps. (maybe ask to resubmit if they don't receive an email) https://test.simplereport.gov/sign-up/thanks

**Comment by LGFranklin** [comment]
We want to create a way for users to ensure they input the correct email address. 
We DO NOT want them to resubmit a form because it would create a duplicate entry of their information.

To address this, we want to update the success message. It currently shows this: 
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/12168e69-1528-4a37-aee5-8e8715fcdcaf)

We want to amend it to indicate to users that they should have received an email with more information about next steps. If they do not receive it, they should contact our support team. 

Something to the effect of...

Next step: Check your email
We just sent an email to the address you included in this signup form. This includes important information about Identity verification as well as some helpful videos and resources to help you learn more about SimpleReport. If you did not receive an email, please contact XYZ@.com

**Comment by LGFranklin** [comment]
@LGFranklin will follow-up with Rebecca on content

**Comment by Rebecca-LM** [comment]
@LGFranklin when is this needed? I should have time tomorrow.

**Comment by LGFranklin** [comment]
@Rebecca-LM Thank you --- the sooner the better so if you are able, it would be top priority to get it tomorrow.

**Comment by sparkle-usds** [comment]
Can we surface the email they provided to them in that message?

e.g. We will be sending an email to {EMAIL ADDRESS PROVIDED}. If this is not the correct email address, or you don't see a message in your inbox or spam, please let us know at SUPPORT@

**Comment by LGFranklin** [comment]
We discussed that. The short answer *yes*, but it will be a different effort and require additional/ different engineering work. I will add it as another item in the backlog

**Comment by Rebecca-LM** [comment]
@LGFranklin suggested copy here:

**Next step: Check your email**

We just sent an email to the address provided. It includes important information about how to complete your SimpleReport identity verification, required for all users. 

Didn't get the email? Check your spam folder then contact XYZ@.com.
