### ISSUE TITLE
Send users an email before their account locks out due to inactivity

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1340]
Currently accounts are locked out after 60 days of inactivity. 

Users should receive an email at 30 days, 53 days and 59 days of inactivity letting them know the their account has been inactive for X days and will be disabled on Y date. This can be accomplished using[ Okta's Automations](https://hhs-prime-admin.okta.com/admin/lifecycle-automation#tab-policies)

**Comment by LGFranklin** [comment]
@Rebecca-LM I'll send you an invite to talk through this one.

**Comment by Rebecca-LM** [comment]
@LGFranklin have a look below and lmk what you think!


[30 days] **Subject: SimpleReport account status**

Hi [first name],

We wanted to let you know that your SimpleReport account has been inactive for **30 days**. Please keep in mind that all accounts are locked after 60 days. To reactivate your account, simply log in to SimpleReport.

[Log in to SimpleReport]

[53 days] **Subject: SimpleReport account status reminder**

Hi [first name],

We wanted to remind you know that your SimpleReport account is currently inactive. Please keep in mind that all accounts are locked after 60 days. To avoid being locked out, you'll need to log in **within 7 days.**

[Log in to SimpleReport]

[59 days] **Subject: SimpleReport account inactive**

Hi [first name],

This is your final reminder that your SimpleReport account is currently inactive. You have **one more day** to log in to your account to reactivate it -- after that your account will be locked.

[Log in to SimpleReport]

**Comment by LGFranklin** [comment]
Thanks, @Rebecca-LM 
I've been doing some digging around Okta to make sure we're communicating the correct thing here. Based on what we have in the automations, we disable the account, which suspends the user. 
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/83ad46ff-ef13-4209-a459-945cc3912e9a)

A suspended account recovery is different than a locked out account recovery. Based on this, it strikes me that WE v the org admin have to unsuspend or reactive the account v a self-recovery option. Is this correct?
https://help.okta.com/en/prod/Content/Topics/users-groups-profiles/usgp-suspend.htm

Since this would be a different path to recovery and not the same as lockout, I think we want to reflect that. Also, I don't think we want to say that their account is inactive. That might signal to them that it won't work v that they just haven't logged in. I made some suggestions here, referencing security measures. 

@timothybest-usds Could you confirm this? This might add a burden to support@ if there are many requests to unsuspend the account, but I *think* that is the best/ only option at this point... 

**30 ****days**
We noticed that you haven't logged into your SimpleReport account for 30 days. As part of our security measures, we suspend accounts that haven't been accessed in 60 days. To keep your account active, simply log in to SimpleReport.

**53** **days**
We wanted to send another reminder about your SimpleReport account. As part of our security measures, we suspend accounts that haven't been accessed in 60 days. To keep your account active, you'll need to log in within 7 days.

**59** **days**
This is your final reminder about your SimpleReport account is currently inactive. As part of our security measures, we suspend accounts that haven't been accessed in 60 days. You have one more day to log in to your account to keep it active -- after that your account will be suspended.

**60** **days**
As part of our security measures, we suspend SimpleReport accounts that haven't been accessed in 60 days. Your account is currently suspended. To start using SimpleReport again, please contact support...

**Comment by Rebecca-LM** [comment]
@LGFranklin got it. Updates below (used a bit of your language mixed with mind and included subject lines).

**[30 days] Subject: SimpleReport account status**

Hi [first name],

We noticed that you haven't logged in to SimpleReport for 30 days. For security reasons, all inactive accounts are locked after 60 days. To keep your account active, simply log in to SimpleReport.

[Log in to SimpleReport]

**[53 days] Subject: SimpleReport account status reminder**

Hi [first name],

We wanted to remind you that your SimpleReport account is currently inactive. For security reasons, we suspend accounts that haven't been accessed in 60 days. To keep your account active, you'll need to log in within 7 days.

[Log in to SimpleReport]

**[59 days] Subject: SimpleReport account final reminder**

Hi [first name],

This is your final reminder that your SimpleReport account is currently inactive. For security reasons, we suspend accounts that haven't been accessed in 60 days. You have one more day to log in to your account to reactivate it -- after that your account will be suspended.

[Log in to SimpleReport]


**[60 days] Subject: SimpleReport account suspension**
As part of our security measures, we suspend SimpleReport accounts that haven't been accessed in 60 days. Your account is currently suspended. To start using SimpleReport again, please contact our support team at xy@xy.com.

**Comment by Rebecca-LM** [comment]
@LGFranklin lmk if anything else is needed on my end for this one.

**Comment by Rebecca-LM** [comment]
@LGFranklin should we close this one?

**Comment by LGFranklin** [comment]
Nope! Working on it now! Esp since suspensions are going up.

**Comment by LGFranklin** [comment]
<div style="background-color:#fafafa;margin:0"> 
  <table style="font-family:'proxima nova' , 'century gothic' , 'arial' , 'verdana' , sans-serif;font-size:14px;color:#5e5e5e;width:98%;max-width:600px;float:none;margin:0 auto" border="0" cellpadding="0" cellspacing="0" valign="top" align="left">
    <tbody>
      <tr align="middle">
        <td style="padding-top:30px;padding-bottom:32px"><img src="${oktaLogoUrl}" height="37" /></td>
      </tr>
      <tr bgcolor="#ffffff">
        <td> 
          <table bgcolor="#ffffff" style="width:100%;line-height:20px;padding:32px;border:1px solid;border-color:#f0f0f0" cellpadding="0">
            <tbody>
              <tr>
                <td style="color:#5e5e5e;font-size:22px;line-height:22px"> Notification for ${f:escapeHtml(user.firstName)} ${f:escapeHtml(user.lastName)} </td>
              </tr>
              <tr>
                <td style="padding-top:24px;vertical-align:bottom"> Hi ${f:escapeHtml(user.firstName)}, </td>
              </tr>
              <tr>
                <td style="padding-top:24px"> This is an important notification for you. </td>
              </tr>
              <tr>
                <td style="padding-top:24px"> Please contact your Okta administrator if you have any questions. </td>
              </tr>
            </tbody>
          </table> </td>
      </tr>
      <tr>
        <td style="font-size:12px;padding:16px 0 30px 50px;color:#999"> This is an automatically generated message from <a href="http://www.okta.com" style="color:rgb( 97 , 97 , 97 )">Okta</a>. Replies are not monitored or answered. </td>
      </tr>
    </tbody>
  </table> 
</div>

**Comment by LGFranklin** [comment]
Thanks to everyone for the email coding and writing. These are now activated on Okta.

**Comment by timothybest-usds** [comment]
Done.
