### ISSUE TITLE
BUG: PersonForm DOB input field allows 6 numbers for "YYYY"

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1398]
**Current experience:** The DOB field currently allows users to input 6 digits for YYYY.
**Expected experience:** DOB input field should only allow 4 digits for YYYY. 

Alicia Update- also add some validation the year is not in the future or too far in the past
- [ ] Add validation that the year is not in the future
- [ ] Add validation that the year is greater than 1900

Note that the form _validation_ does the right thing and does not allow for illegal date values; it's just the input.

https://images.zenhubusercontent.com/302387839/1175448b-ca4e-44ee-ab9a-aa7aab9f0660/screen_recording_2021_04_21_at_4_33_17_pm.mov

**Comment by nullflux** [comment]
Per @nickscialli-usds this is just a matter for setting a `max` on the native date input element

**Comment by aliciabeckett-gov** [comment]
The DOB is not being validated to be >1900 and <current date.

Please complete the rest of the ticket before closing @cdevent @timothybest-usds

**Comment by cdevent** [comment]
@aliciabeckett-gov Validation is working correctly, however, it's a known issue when the `new Date()` function transforms value from input to date format and parse **0012** as **2012** that's why it's not alerting error.
 
I'll look into this problem closer tomorrow, will try to find some workaround.

**Comment by aliciabeckett-gov** [comment]
﻿Thank you!

From: Volodymyr Onofriichuk ***@***.***>
Reply-To: CDCgov/prime-simplereport ***@***.***>
Date: Tuesday, June 1, 2021 at 10:36 AM
To: CDCgov/prime-simplereport ***@***.***>
Cc: "Beckett, Alicia (CDC/OCOO/OD)" ***@***.***>, Mention ***@***.***>
Subject: Re: [CDCgov/prime-simplereport] BUG: PersonForm DOB input field allows 6 numbers for "YYYY" (#1398)


@aliciabeckett-gov<https://github.com/aliciabeckett-gov> Validation is working correctly, however, it's a known issue when the new Date() function transforms value from input to date format and parse 0012 as 2012 that's why it's not alerting error.

I'll look into this problem closer tomorrow, will try to find some workaround.
