### ISSUE TITLE
Allow patients to access test results in Spanish

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1470]
Roughly 40% of test results are currently being texted to patients (per analysis done on 4/26/21). Test results should be accessible in the patient's preferred language so that they can interpret the result and take appropriate action. Spanish is the second most spoken language in the U.S., so we will start with Spanish and add support for additional languages as we learn more from our analytics (preferred language responses + DAP).

Tasks:

- [x] Design language switcher allowing patients to toggle between English and Spanish
- [x] Investigate whether we can detect language based on browser settings and display result in that language by default
- [ ] Translate test results into Spanish

How it works (v1):
- [ ] Language display (globe icon + site language) in header will display when user lands on Results screen
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/340c968d-0313-4a99-8aac-56b6ba2c2ab9)

- [ ] We will automatically detect the browser language settings and display the test result in English or Spanish. If we cannot detect any language settings, we will default to English.

- [ ] When user hits the language display (globe + site language), a drop-down will appear with the language options. The current language will be selected and will appear at the top of the list. Languages will be listed using the foreign name of the language (how they’re written in each particular language that they apply to) rather than the current language of the website (i.e. Español, not Spanish).

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/7b308f93-234f-4400-b29a-6888a6ad37d5)

- [ ] The currently selected site language will always appear first in the language selector. For example, if the user is viewing the result in Spanish, the dropdown will display "Español" followed by English. This will be more important when we start supporting more languages.

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/60042e6a-2f6e-4939-9645-ab552df20d69)

Future Needs (v2 and beyond):
- [ ] Apply language selector to Terms of Service
- [ ] Apply language selector to DOB Authentication

**Comment by hmyers-cms** [comment]
From duplicate #1555

Roughly 40% of test results are currently being texted to patients (per analysis done on 4/26/21). Test results should be accessible in the patient's preferred language so that they can interpret the result and take appropriate action. Spanish is the second most spoken language in the U.S., so we will start with Spanish and add support for additional languages as we learn more from our analytics (preferred language responses + DAP).

Note: Implementation is pending translation of test results into Spanish. Until then, this should be hidden behind a feature flag.

How it works (v1): (interactive prototype here)

 Language display (globe icon + site language) in header will display when user lands on Results screen. When the page is in English, the language display will say "Español"; When the page is in Spanish, the language display will say "English".

 We will automatically detect the browser language settings and display the test result in English or Spanish. If we cannot detect any language settings, we will default to English.

Future needs (probably should be part of an epic for multiple language support):

Allow patients to access global patient app components in Spanish (e.g. Terms of Service, DOB authentication)
Allow patients to self register in Spanish
Allow patients to answer test questionnaire in Spanish
Allow patients to do all of the above in languages other than English and Spanish (TBD) - (design for 2+ languages here - an extension of what's in this ticket)
