### ISSUE TITLE
The app zooms in when you click into the search box

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1605]
### Description
When you click into the search box, the app zooms in slightly which cuts off some of the content. 

### Steps to reproduce
1. Open Safari on mobile
2. Go to localhost:3000
3. focus on the search box in the test queue
4. The app zooms in

### Expected behavior
Focusing on an input should not change the zoom level of the application

### Additional context
- Safari browser where it will zoom in on focused inputs when the font size is less then 16px. We should increase the font size of all inputs to 16px
- https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone

**Comment by maya** [comment]
Fixed in #1643.

Also, @cdevent if you could link the issues using [GitHub's supported keyword format](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) in your pull request's description, it would be greatly appreciated. For example, adding `Closes #10` in the PR will auto-close the issue on merge, so we don't have to close manually.
