### ISSUE TITLE
Test result submission is failing on patients with invalid phone numbers

### ISSUE THREAD

**Issue by jeremyzitomer-usds** [CDCgov/prime-simplereport#1651]
On some `SubmitTestResult` operations, submission is failing because phone number validation is failing on the patient's phone number. We need to figure out a way to migrate invalid phone numbers to another working phone number (or nullify them completely) so that tests can be submitted for those patients.

## Acceptance Criteria
* SR Users should be able to save test results no matter what; invalid phone number exceptions should not short-circuit this flow
* In the event of an invalid phone number, provide some feedback to the user

@katiealoisi to follow up with design (complete - below): **there is some complexity to receiving a successful result _however_, we could not deliver this result to the patient** 

If phone number is invalid and texting fails, the SR user sees this modal dialog informing them that the result was not delivered to the patient and that they need to take action to inform them of their COVID status. 

![image](https://user-images.githubusercontent.com/66079940/119503243-c2443400-bd38-11eb-8b38-f043e3a300b1.png)

**Comment by katiealoisi** [comment]
Including a proposed design, but would like to get @Rebecca-LM's input on the copy first.

**To recap the problem:** If a patient elects to receive their test result via text message but has an invalid phone # on file, the text message will not be delivered to the patient. We need to let the SimpleReport user know that the text failed so they can take appropriate action (e.g. update the phone number, print the result, or otherwise communicate the result the patient). This is especially important if the patient tests positive and expects to receive their result via text (but never does). The SR user needs to know they never received their result so they can inform them and they know their status.

Possible solution: If the phone # is invalid and texting fails, the SR user sees this modal dialog informing them that the result was not delivered to the patient. It's a little complex because the result SUBMISSION (to public health) was successful, but the result delivery to the PATIENT was not. We need to make sure this distinction is clear. Can you take a look at the language and let me know what you think? 

If anyone has Qs or suggestions re the design, please raise them. Hopefully this won't be a very common issue now that we have phone number validation. Also tagging @hmyers-cms 

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/ca052330-a637-40ec-9600-f77e165609b8)

**Comment by katiealoisi** [comment]
Chatted with Rebecca about this ticket and will have updated copy by tomorrow AM!

**Comment by Rebecca-LM** [comment]
@katiealoisi here's my pass on the content below. Lmk what you think!


**Incorrect phone number**

We're unable to send **Last name, First name**'s  test results to them via phone because their  phone number is incorrect or can't receive text messages. (Results were sent successfully to the public health department.)

Please update **First name**'s phone number and contact them directly to inform them of their COVID-19 status.

**Comment by katiealoisi** [comment]
Thx @Rebecca-LM! Updated the body of the ticket with this copy. This is ready for engineering!
