### ISSUE TITLE
Spike: Send Touchpoints feedback content to email

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#1684]
Explore what would be the level of effort of sending [Touchpoints](https://touchpoints.digital.gov/) feedback content to an email.

Touchpoints sends an email notification when there's a new submission, but that email doesn't contain any content. Their ATO was predicated on not sending the feedback content to an email, but it's accessible via their OpenAPI.

Touchpoints API: https://github.com/GSA/touchpoints/wiki/API

**Comment by emmastephenson** [comment]
Would it be ok to send this as a daily (or hourly) digest of content? Or is the goal to send an email with content as soon as the form is submitted?

Looking at the Touchpoints API, it seems as though they only have an endpoint that returns all responses for a given form. We could set up a job to ping that endpoint once a day and filter by recently-submitted responses, but it'd be harder to be notified as soon as new content comes in. I also don't know if the Touchpoints team has restrictions on how many times you can ping their API in a single day; they might have an issue if we start requesting all form responses every few seconds.

**Comment by maya** [comment]
Let's ask @ryanwoldatwork. Ryan, thoughts on the above?

**Comment by ryanwoldatwork** [comment]
Per Touchpoints' Security Plan, the contents of a submission are not to be pushed to another system (because PII may potentially be included - even if not intended and the user is instructed not to).

Polling the API every few minutes shouldn't be an issue. I'd suggest not polling it every few seconds.

I'm looking into webhooks support as well, which might help this scenario - being able to programmatically receive a notification, then poll to pull the data when prompted.

Always open to chat!
