### ISSUE TITLE
SPIKE: Define a DB Rollback Strategy for Cloud Environments

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#1794]
Currently there is no way to perform database rollbacks other than to manually generate the commands that liquibase _would_ have run and to execute them manually. We can do better than this. This ticket is a SPIKE to determine what the SOP should look like, and will be followed up with a DevOps ticket to formalize this process

- [x] Develop a strategy and document it

- [x] Create a new ticket to implement it

Timebox: 1.5 days

**Comment by jdorothy** [comment]
Assumptions: we can't publicly expose a given database. Meaning, any solution needs to use an Azure resource that can talk to the DB - nothing from local machines or Github.

Potential solutions:
* A write-up on how to use the Liquibase CLI from a VM to roll back a given DB
* Using an Azure Function to use the Liquibase CLI to roll back a given DB

**Comment by jdorothy** [comment]
I think the following is probably the most maintainable/repeatable way to do this:
* Start using [tags](https://docs.liquibase.com/commands/community/tag.html) for new changesets going forward; potentially backfill existing changesets as well?
* Update the rollback workflows to accept a `tag` parameter (required? default value of most recent?)
* Use the Liquibase CLI to generate a SQL changeset file to roll back to the provided `tag` value
* Parameterize the `spring.liquibase.changeLog` setting to conditionally point to the file just generated
* Deploy as normal - the rollback changeset will be executed instead of the standard `db.changelog-master.yaml`, rolling back to the specified `tag` in a cloud environment

**Comment by jdorothy** [comment]
Ticket created: #2177
