### ISSUE TITLE
AccountRequestController and UserAccountCreationController do not create AuditLog entries

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#1925]
Our Spring REST controllers should produce audit logs. The PatientExperienceController does so using this annotation:

```
@PostAuthorize("@restAuditLogManager.logRestSuccess(#request, returnObject)")
```

AccountRequestController and UserAccountCreationController are not so annotated, and do not appear to have explicit audit logging built in. These controllers are used mostly for anonymous requests, so one might argue that they don't need to appear in the log... but we should probably cover our bases

**Comment by emmastephenson** [comment]
What is our policy around PII or sensitive data in the audit log? I don't think it'll be possible to record the raw request as we're doing elsewhere, because the request body in UserAccountCreationController will sometimes contain sensitive information like password, recovery question, or user phone number. Is it enough to log something to the effect of "Password reset for user $OktaUserId"?
