### ISSUE TITLE
Create Self-registration links for all  new, organizations & facilities

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1942]
### Background

We released the patient self-registration feature to a few beta partners, and it's going well. To release this feature to everyone we need to create self-registration links for all existing and new orgs/facilities.

Links should be short and easy, so 5 characters of A-Z and 0-9, except for ones that are difficult. Let's not be case sensitive.  Even 30^5 is over 24 million combinations. Strings need to be unique.

The work to show the links to the organizations is in ticket #1682.

### Work Required
- [ ] Create new links for new organizations and facilities as they are created

Note: Continue to support existing links for beta customers

 
### Mock Up

![Screen Shot 2021-06-30 at 1.47.00 PM.png](https://images.zenhubusercontent.com/5ff8bf4767136734d905d155/09082671-2e1d-4093-b10e-bee6970bd834)

**Comment by nickscialli-usds** [comment]
@aliciabeckett-gov @nullflux Since we previously had total control over making the self-registration links, we didn't have to worry about whether the organization was verified or not&mdash;we just would never have made a link for an unverified org. Now that we'll be making a link when organizations are created, I think we need to add a small piece of work to this ticket to make sure patient self-registration links don't work for unverified organizations or their facilities.

**Comment by aliciabeckett-gov** [comment]
@nickscialli-usds that's a great point! Let's add that work to the ticket.
