### ISSUE TITLE
Revise error messages within the Okta account creation flow

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1966]
As a user, when I'm presented with an error message, I want the content to tell me the error and how to remedy it.

Currently, some of Okta's default error messages are confusing and unclear to users. We need to revise the ones below:

- [ ] When users submit an incorrect one-time security code
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/7029454b-a37f-47a0-a57f-768c415bc47f)

- [ ] When users submit an unvalidated phone number for SMS
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/119415e4-e91f-4f52-807a-8333ac68aa6e)

- [ ] When users requested a phone call and make another request too quickly, the message refers to an SMS
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/c0e0299d-b479-4d36-92ad-dcebe93d0452)

**Comment by Rebecca-LM** [comment]
@LGFranklin some questions on this for you:

- **When users submit an incorrect one-time security code**: This looks ok to me. Is there other information they need to know?
- **When users submit an unvalidated phone number for SMS**: What info do they need here? Is it formatted incorrectly, or what exactly is wrong with the example given?
-  **When users requested a phone call and make another request too quickly, the message refers to an SMS**: Would this be solved by deleting the first sentence referring to SMS and keeping the second sentence telling them to wait 30 seconds?

**Comment by LGFranklin** [comment]
@emmastephenson Can you post the text you created for these so @Rebecca-LM can see what's in there now?

**Comment by emmastephenson** [comment]
Sure! Here you go. Those images are also slightly outdated, I did make some edits since then, so I've added the current copy below.

1. No, I can't think of any more specific information. Okta varies between 5 and 6 digit codes too, so we unfortunately can't even say something like "make sure your code has 6 digits". The current message is "The provided security code is invalid."
2. There are a couple of reasons the phone could be wrong here, but the most common one is that it's a landline or otherwise can't accept text messages. The other option is that it's an international phone number that can't get US texts. There's also two different pieces of validation here - the frontend validates that the string is the correct length, and the backend does the landline validation. The current backend message is "Invalid phone number. You must enter a phone number capable of receiving text messages."
3. I updated this copy to remove the SMS bit: "A security code was recently sent. Please wait 30 seconds before trying again." 

I'd love some feedback on the current messages though! We were just trying to get this out the door, so I'm sure there's room for improvement.

**Comment by Rebecca-LM** [comment]
Thanks for the additional info, @emmastephenson. Sounds like we can't actually give users too much useful info in these situations, so I just have small tweaks. Do let me know if things change so we can provide more useful info in the future! Below are my suggestions/questions for each. Lmk if you have any feedback, etc.

1. "Invalid security code."
2. Is it correct to assume that just cell phones can get text messages? If that's the case 99% of the time let's add the word mobile here. If not take out and keep the rest. "Please enter a mobile phone number that can receive text messages."
3. When we say "A security code was recently sent", do we mean we just called with the security code? Or is it possible the call hasn't gone through yet? I suggest: "We're sending over a security code. Please wait 30 seconds before trying again."

**Comment by Rebecca-LM** [comment]
@emmastephenson bumping this for you. Lmk if you have feedback on what I sent above!

**Comment by emmastephenson** [comment]
Thanks! These all look good to me, I'm planning to implement later this afternoon :) 

For #2, yeah, I think it's a safe assumption that only cell phones can get texts.
For #3, it's possible that the call or text hasn't gone through yet. Your suggestion looks great.

**Comment by Rebecca-LM** [comment]
Great! And thanks!
