### ISSUE TITLE
Single character names don't appear in conduct test results

### ISSUE THREAD

**Issue by vz3** [CDCgov/prime-simplereport#2000]
To replicate:
Create a user on the front end with a single character first name or last name

Attempt to search for that user from conduct test screen

It's my understanding that single character names can be legal names in the United States, but a likely edge case.

![image.png](https://images.zenhubusercontent.com/57322f73bf93871ccd9ad030/67ae7778-3bcb-41e0-a173-cf83418af620)

**Comment by aliciabeckett-gov** [comment]
We're not going to fix this. We made an explicit decision to live with this since we don't want to return search results with only one character. You are able to search for a patient by both first and last name, and it is **extremely** unlikely that a person will have a single character for both their first and their last name.
