### ISSUE TITLE
Implement more flexible validation error messages on the frontend

### ISSUE THREAD

**Issue by nickscialli-usds** [CDCgov/prime-simplereport#2123]
### Description

Currently, we implement our own validation messages to accompany `yup` validation errors. This solution is inflexible&mdash;it only allows one error message per input field.

### Proposed solution 

Use built-in `yup` error handling to allow for dynamic error messages based on what validation actually failed.

**Comment by nathancrtr** [comment]
If this work will involve any changes to error messages on the person form, we will require Spanish translations of the updated copy so that self-registration can remain fully internationalized.

Whoever works this ticket should contact @aliciabeckett-gov for assistance in collecting the translated text.
