### ISSUE TITLE
Update Styling of Clear Filters buttons

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#2156]
Figma designs: https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=3589%3A12410
Fontawesome icon: https://fontawesome.com/v5.15/icons/sliders-h?style=light

![Screen Shot 2021-08-11 at 2.26.55 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/0c3fe772-8070-4448-ae3b-5d2be3cc9b66)

NOTE:
We are using the same padding as specified by the USWDS

**Comment by kenieh** [comment]
FYI, planning to work on the designs and get them on here after wednesday's bug hunt / before Thursday grooming

**Comment by kenieh** [comment]
Note: The disabled state of the clear filter button should be used when no filters have been applied.

Also, the design team discussed this, and we think we should take out the "Clear Filters" button from the button page. Since there's only one filter option on People's page right now (which is essentially a search bar), the "Clear Filters" button is redundant. When users want to clear the name search, they can click the "x" in the search component.

![Screen Shot 2021-08-12 at 8.37.25 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/07235611-e460-48f3-983a-4821da6a6564)
