### ISSUE TITLE
[BUG] Some questions on AoE are optional but still marks form as pending

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some fields on the AoE form aren't required by the frontend, but the form will be marked pending until they're added (i.e. pregnancy). 

### Steps To Reproduce

1. dev.simplereport.gov
2. Add person to queue, but don't fill out all the fields
3. Status is marked as pending, but because the questions on AoE aren't marked with required, users can't tell which fields need to be edited

### Expected Behavior

Form should tell users which fields are needed to get form to "complete", or mark the status as "complete" once they've filled out the required questions.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by kenieh** [comment]
The design team thinks that when "required" form fields are filled out and "optional" fields are not filled out, the Questionnaire should "completed" NOT "pending". This is the expected behavior of the Questionnaire tag.

"Symptoms" should also have its asterisk removed. According to the data catalog (https://www.simplereport.gov/getting-started/public-health-departments/simplereport-data-catalog/), symptoms and pregnancy are optional fields.

**Comment by kenieh** [comment]
Adding Tech Debt tag as this should be resolved in the code.
