### ISSUE TITLE
[BUG] Additional phone number fields not marked as required and are not validated until dirty

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#2275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

*** This is written based on validation that is done in a not-yet-merged PR.  Ensure https://github.com/CDCgov/prime-simplereport/pull/2213 is merged before confirming this bug ***

When adding additional phone numbers, the number and type (mobile/land) are not marked as required but are actually required.  The form can be submitted with invalid data and the invalid request is not handled until hitting a db constraint.

### Steps To Reproduce

1. visit patient self-registration, accept terms
2. fill out form with valid data
2. click "Add another number" (do not dirty the fields)
3. scroll down and press "Submit"
3. the request is submitted, and results in a backend 500 error

### Expected Behavior

All of:

1. When visible, the additional phone number fields should be marked as required the same way the primary one is.
2. The frontend should not submit the form until the phone number and phone type of additional phone numbers are entered or the items are removed
3.  The backend should validate the input and reject a request sent with an empty phone number and/or type rather than letting it hit a db constraint (`org.postgresql.util.PSQLException: ERROR: null value in column "number" violates not-null constraint` since both `type` and `number` are null)

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by nathancrtr** [comment]
This is a great callout. For a little more background, any additional phone numbers _should_ be optional:

<img width="1245" alt="Screen Shot 2021-09-09 at 4 55 27 PM" src="https://user-images.githubusercontent.com/27730981/132761346-f2de8825-031e-4b53-b186-83cecfc99944.png">

The intended behavior is implemented at [personSchema::areValidPhoneNumbers](https://github.com/CDCgov/prime-simplereport/blob/a1c72c4f0c7268c1a229a79b8fca69412e142250/frontend/src/app/patients/personSchema.ts#L89-L117).

The way the add and edit patient forms enforce this optionality is by filtering out any empty `phoneNumbers` from the GraphQL mutation variables before making that request (see [here](https://github.com/CDCgov/prime-simplereport/blob/a1c72c4f0c7268c1a229a79b8fca69412e142250/frontend/src/app/patients/AddPatient.tsx#L245-L249)). The bug described in this issue is a result of the self-registration form _not_ performing this filtering before sending the request to register the patient.

Given that this would represent a _third_ place to re-implement the same logic, whoever picks up this ticket should consider DRYing that out in some way - most likely by having the server robustly handle empty additional phone numbers without blowing up.
