### ISSUE TITLE
Add a maintenance banner to the static site

### ISSUE THREAD

**Issue by nickclyde** [CDCgov/prime-simplereport#2315]
### Description
We currently don't have a good way of informing our users that there is currently an outage in the app and that the engineers are working on a resolution.

### Proposed solution 
Add a maintenance banner to the static site with a switch we can flip on whenever we are resolving an outage.

### Additional context
- This request came of the [postmortem for the Apollo Client Upgrade Outage](https://github.com/usds/prime-simplereport-docs/pull/24)
- Max spend one day on spec

**Comment by emmastephenson** [comment]
Met with @bmaden-usds and @nickclyde today to discuss the details around this banner. Decided on a REST-based implementation that will allow us to update the banner from the super admin page, without waiting for a deployment of either the app or the static site. 

### Implementation Details
We'll add a REST endpoint to the app that functions as a status checker, and is pinged on every load of the static site or app. (If this slows down the app too much we can only load it at app sign-in, but we'll definitely want it on the static site.)
This endpoint will report if an outage/maintenance banner should be shown. If it should be displayed, the endpoint will return the severity level of the incident and the user-facing message that should be displayed.

A second endpoint will be added to activate the maintenance banner. This will take in the severity level and user-facing message for the incident.

We'll add an option on the super-admin page to activate and deactivate the maintenance banner. 

Finally, we'll add the skeleton maintenance banner to the static site and app, so that it's ready to be displayed if activated.

Open questions: should we store the maintenance banner text and severity level in the database? If so, where?

**Comment by emmastephenson** [comment]
New plan after another meeting with engineers on 9/2.

There are concerns about putting a backend dependency in place for the maintenance banner. It would be called on every load of the static site, and if the backend was down (not unlikely if we're in the middle of an incident) the status banner might not work correctly.

New solution is hopefully more lightweight, while still enabling us to deploy the banner rapidly.

The new plan is to add a json blob to our repo (`outage.json`?) that contains the message and severity level for the incident.
We'll add a Github Action to enable/create the blob with a single button. (This will need to take in text input for both the message and severity level)
The action can be re-run to disable the banner by removing the blob. 
The action should only take a few seconds to run, so we're not waiting for a full deployment of the app to pass messages onto users.

**Comment by nickclyde** [comment]
Should this be environment specific, or apply across all environments? I think the latter would be a lot simpler to implement

**Comment by emmastephenson** [comment]
> Should this be environment specific, or apply across all environments? I think the latter would be a lot simpler to implement

I think applying across all environments is fine for now!
