### ISSUE TITLE
More clearly describe where users will go / what they will do upon successfully creating their account

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2407]
Language on the button should say something like "Log in to start using the app"

**Comment by emmastephenson** [comment]
@emmastephenson to find screenshot

**Comment by emmastephenson** [comment]
This is currently the final screen of account creation:
![Screen Shot 2021-08-24 at 3 14 52 PM](https://user-images.githubusercontent.com/80282552/130697230-a87f868f-42be-4ed2-b3a6-720e0f209214.png)

**Comment by emmastephenson** [comment]
And that "continue to SimpleReport" link takes you back to simplereport.gov

**Comment by Rebecca-LM** [comment]
This one is tough because the button doesn't take you to log in, it does what is says and takes you to SR. At this point does the user have their account, or do they still have to start the flow to create it?

@emmastephenson what do you think about changing the sub head text instead, but keeping the CTA? We'd keep "to your account" depending on if they have one at this point, or not.

"To start using SimpleReport, visit the website to log in (to your account)."

**Comment by emmastephenson** [comment]
Yep, at this point users will have just completed account setup (so they'll have set their password, security qs, and MFA enrollment.) I like changing the subhead text instead of the CTA, I'll make that update.
