### ISSUE TITLE
Reduce aggregate size of DB connection pools

### ISSUE THREAD

**Issue by jdorothy** [CDCgov/prime-simplereport#2635]
### Description
See #2181 for more details. We need to pare down the number of connections used by the application and Metabase connection pools.

### Proposed solution 
* Reduce the _aggregate_ connection pool size to 10 for each environment.
* Reduce Metabase's connection pool size to < 5. Investigation might be required for optimal sizing.

**Comment by emmastephenson** [comment]
Rin and Josh to sync on this, then PR will go up for review.

**Comment by rin-skylight** [comment]
As it turns out...deploying this to PROD without the associated Spring Boot dependency upgrades makes the production database very unhappy. We effectively halve the number of available connections without doing anything to mitigate our connection retention issues. Time to service degradation was three hours.

Moving this item to "Thawing", and adding a dependency on the Spring Boot upgrades. We can revisit this once those changes are out, **AND** they've had a little time to sit in production without any correlated issues.

**Comment by rin-skylight** [comment]
Given the increased traffic through SimpleReport, the team has decided to abandon reducing the overall size of DB connection pools, instead opting to increase them. The Metabase ask for this ticket was addressed as part of #3141, and was merged into Production on 21 December 2021. This item can be considered "Closed".
