### ISSUE TITLE
Add graphql mutation for site admins to change a user's organization (backend)

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#2676]
### Description

We service a lot of support requests where multiple users have created organizations and want to join together to use one of them.  Currently, to fix these we have to use the okta admin console to manipulate group membership manually.  This is tedious and error prone.

### Proposed solution 

* Create a new graphql mutation to modify a user's group membership
  * Should only be usable by site admins (`RequireGlobalAdminUser`)
  * Take user uuid and new organization uuid as as parameters
  * Remove user from all current organization-level groups
  * Add user to the `NO_ACCESS` group of the requested organization

The group selection can be done with the organization selector already used on other admin pages (such as tenant data access).

The user uuid can be looked up in metabase and provided here in a text input.  This isn't ideal, but adding a way to retrieve the user's uuid is beyond the scope of this ticket.

**Comment by emmastephenson** [comment]
Some alterations and context to the original ask:

- We should be able to use the user's email address instead of UUID in the body of the request (we can use the ApiTable to go from email -> UUID)
- The ideal outcome after running the mutation is that the user has been added to the organization with the appropriate permission levels and facility access. We'll normally expect them to be part of at least 3 different Okta groups: 
    - `NO_ACCESS` (this ensures the user will show up in the sidebar list of Manage Users for the org)
    - one of `STANDARD`, `ADMIN`, or `ENTRY_ONLY` permission
    - either a specific list of facilities, or the `ALL_FACILITY` group
- Adding them to a facility in addition to organization means we'll probably want the mutation to look something approximately like the following:
```
mutation moveUserToDifferentOrg ( 
email: String!,
newOrganization: UUID!
permissionLevel: Role!
facility: [UUID]
allFacilities: boolean
}
```
Ultimately, the acceptance criteria for this ticket is that we have a graphQL mutation that eliminates the need for engineers to go into Okta and manually adjust user groups in order to move users between organizations.

**Comment by emmastephenson** [comment]
I will create a new ticket for this and the associated frontend piece with additional context, and we can prioritize appropriately from there.
