### ISSUE TITLE
Add frontend telemetry to track api_user UUID, org id, and facility id

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2786]
### Description
We can't determine the root cause of the high rate of `pxp/link/verify` failures without better understanding user behavior. Are the same subset of users trying expired links over and over again, or do we actually have a 75% failure rate for those links?

### Proposed solution 
Add frontend telemetry to track api_user UUID, organization id, and facility id. These should give us a better picture of user behavior. 
Note that the pxp/link/verify is performed as an anonymous operation (i.e. they're not api_users) so we may also want to send information about the session or client IP.

### Additional context
https://skylight-hq.slack.com/archives/C01LTSNKEPP/p1634140975453200?thread_ts=1634075797.419800&cid=C01LTSNKEPP

**Comment by jdorothy** [comment]
It turns the only thing we can easily do on the front end is track the client IP (by enabling it in App Insights). Unfortunately, tying that to backend requests is a lot harder, since the client IP is determined by the App Insights telemetry ingester rather than by client-side code, and the backend is a separate service that isn't automatically passed the frontend request telemetry information.

However, this combined with the `operationId` column in App Insights logs and the full App Insights Transaction views should be enough to determine whether a lot of our exception bursts are related to a particular user or operation, rather than a systemic code issue.

I'm looking into sending the session ID as a header to the backend as well, so we can tie everything together.
