### ISSUE TITLE
Investigate if there are duplicate or triplicate of the same organization

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-simplereport#2853]
In trouble shooting a log in problem, I noticed an org was in SimpleReport 3 times. The organization is located in Colorado and would be good to understand if these are 3 separate organizations or 1 organization that signed up 3 times.

![image](https://user-images.githubusercontent.com/35788031/139170086-9a10c8d7-5a53-4940-8ce7-04be9978d1d0.png)

**Comment by emmastephenson** [comment]
This is almost certainly a duplicate organization issue. All three orgs have been identity verified, but one hasn't reported any tests, one has reported 88 tests, and one has over 700 tests. The one with 88 tests stopped reporting at the end of August, and the one with 700+ is still reporting. 

This could be a good candidate to reach out to to understand why organizations make these kinds of errors. 

It's also worth noting that we're doing a lot of work on G&E to cut down on these types of errors - we have designs in progress to update the signup flow to make it clearer that it's organization signup, not user signup, and we've done some work on the backend that will prevent the close name duplicates from being created (so "Silver Heights" instead of "silver heights" can't happen anymore.)

**Comment by mlighdc** [comment]
Thanks @emmastephenson can you outline what the immediate next steps are? Will G&E reach out to the contact to resolve? Will G&E make 1 or 2 of these inactive? The reason I am asking is because timing of these changes have implication with the weekly reports that we sent out. I also opened another ticket with similar implications - [2890](https://github.com/CDCgov/prime-simplereport/issues/2890).

**Comment by emmastephenson** [comment]
Discussed offline - we can mark some orgs/facilities as is_deleted to get rid of issues in state reports.

**Comment by mlighdc** [comment]
@emmastephenson was the team able to delete the Florida org yet? I want to give Florida a heads up if we are not able to do it  this week. I also have to create a new report to sent to them after you have the Is Delete set to true for those orgs/facilities. Thanks!

**Comment by emmastephenson** [comment]
The Better Data team took on the FL deletion work, I'm not sure what the status is there - @tim-skylight, can you provide an update?

It looks like a separate ticket was created in the Better Data backlog for this, so that's probably the best place for updates: https://github.com/CDCgov/prime-simplereport/issues/2914
