### ISSUE TITLE
Reduce the number of calls to Okta's api/v1/app endpoints in organization/facility creation

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3058]
### Description
On 12/1/2021, we we warned by Okta that we'd hit 60% of our rate limit for the /api/v1/app endpoints. Further investigation revealed that:
- this endpoint is mostly (only?) called in organization and facility creation
- the rate limit is 100 per 10s, and resets after that
- The endpoint is called 10x for each organization creation and 6x for each facility creation

### Proposed solution 
We should look to see if the number of calls to this endpoint can be at all reduced. Downloading Okta's syslog gives a more detailed picture of which endpoints are being called, and their SDK docs also list the actual API endpoints associated with each method ([here's an example](https://developer.okta.com/okta-sdk-java/apidocs/com/okta/sdk/resource/application/Application.html#createApplicationGroupAssignment-java.lang.String-)).

As a starting point, we may want to look at removing the [`_app.update`](https://github.com/CDCgov/prime-simplereport/blob/8371ed34fa9ea32abe677b87b2d4a4c0f3f09d80/backend/src/main/java/gov/cdc/usds/simplereport/idp/repository/LiveOktaRepository.java#L447) calls in `createOrganization` and `createFacility`. I suspect that these calls are redundant, as it seems that the [`createApplicationGroupAssignment`](https://github.com/CDCgov/prime-simplereport/blob/8371ed34fa9ea32abe677b87b2d4a4c0f3f09d80/backend/src/main/java/gov/cdc/usds/simplereport/idp/repository/LiveOktaRepository.java#L442) method may also be calling `update`  indirectly.

### Additional context
Slack thread about this issue: https://skylight-hq.slack.com/archives/C01LTSNKEPP/p1638381688311500

**Comment by jdorothy** [comment]
Findings:
- Groups are created/assigned in our code via a `GroupBuilder.buildAndCreate()` and `Application.createApplicationGroupAssignment` pairing
- This pairing happens once per facility creation, and one per _role_ per organization creation
  - We currently have 5 roles: `NO_ACESS`, `ALL_FACILITIES`, `ENTRY_ONLY`, `USER`, `ADMIN`
- We also call a final `Application.update()` at the end of both processes
- So doing the math: each facility creation results in (2 * n) + 1 calls to `/api/v1/apps` (where n = # of roles and assuming n = 1 for facilities)
- We do not have control over needing to iterate over the roles during organization creation (and therefore making multiple API calls), either in the SDK or the API directly, since there is no batch group -> app assignment API operation

Conclusion:
- It _does_ look like we can remove the final `Application.update()` at the end
  - Creating a facility and org in test worked fine without it
  - `Application.update()` calls `PUT /api/v1/apps/{appId}`, which, notably, does _not_ accept any data in the body that would modify group assignments
  - The above two bullet points suggest that this is a no-op and we can remove it
- Even with removing the `Application.update()` calls, we're likely to run into this again as we scale. Some potential mitigations/solutions:
  - Implement delays/exponential backoff/retries rather than failing the whole operation
  - Implement a queueing service that can enforce a rate limit on our terms
  - ?

**Comment by emmastephenson** [comment]
Thanks for the research on this Josh, really appreciate it!

Removing the `application.update()` call seems like a good move for now. For longer-term solutions, Tim B. and I had also talked about potentially moving group assignments out of Okta and handling them within the database. That's obviously a pretty big lift though, so let's maybe hold on any further action until we get better growth estimates for the year.
