### ISSUE TITLE
[BUG] Investigate InvalidTwilioMessageIdentifierException

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#3064]
### Description
We received alerts about an `InvalidTwilioMessageIdentifierException`. An end-to-end transaction report for a sample request can be found in [Azure Application Insights](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7d1e3999-6577-4cd5-b296-f518e5c8e677%252FresourceGroups%252Fprime-simple-report-prod%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%22a4b961d0-53a3-11ec-be96-4fb8cfdbd590%22%2C%22timestamp%22%3A%222021-12-02T19%3A11%3A23.934Z%22%2C%22cacheId%22%3A%22aae82272-884c-4b66-9b60-a3e55f23af8f%22%2C%22eventTable%22%3A%22requests%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A86400000%2C%22endTime%22%3A%222021-12-02T20%3A43%3A51.885Z%22%7D%7D)

### Steps to reproduce
Our hypothesis for why this happens:

1. SimpleReport instructs Twilio to send an SMS to a patient
2. Twilio does not send the message due to service degradation, outage, validation failure, etc.
3. The `ApiException` thrown by the Twilio library is swallowed by `SmsService::sendToPerson` and execution continues
4. `TextMessageStatusService::saveTextMessageStatus` attempts to retrieve a sent text message from the database
5. The message will not be found as it was never sent, and the program will throw an `InvalidTwilioMessageIdentifierException`

### Expected behavior
Determine if this exception is appropriate, interesting, and useful.

If it is not, update the code to more gracefully handle this case so as to not cause un-actionable alerts. (maybe failed text messages need to be represented in the DB?)

If the exception _is_ valuable, evaluate whether it is appropriate to include in PagerDuty alerts.

### Additional context
N/A

**Comment by emmastephenson** [comment]
Closing this for now, as I did some additional research into this with our recent Twilio issues.

This exception is thrown when Twilio can't send a message for some reason, but it's not usually worth a resend attempt. The exceptions are for things like an attempted send to a landline or otherwise unreachable number. We could consider storing these in the database, but it's not terribly necessary as Twilio already stores every failed send & the reason it failed.

This also doesn't alert us of major issues like a Twilio outage or messages being carrier blocked, as Twilio only throws this exception if it attempted to send. We're setting up separate Twilio webhooks to monitor for those issues, see #3296.
