### ISSUE TITLE
Improve the UX for adding a duplicate person to testing queue 

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3103]
### Description
The app crashes without any clear message. when adding a person to the queue that is already in another facility's queue

### Proposed solution 
Show a clear message or disallow operation

### Additional context
https://user-images.githubusercontent.com/4952042/146027587-a57092b7-1314-4f4a-9c36-bd5941897e7a.mp4

**Comment by emmastephenson** [comment]
Solution here is likely to throw some kind of toast to let users know that the patient is already in another facility queue (and potentially share the name of that facility, if possible)

**Comment by Rebecca-LM** [comment]
@emmastephenson what does the user need to do to change their facility? I'm assuming they would want to do that here? What are their options from here on what next action they can take?

**Comment by emmastephenson** [comment]
There's a couple of potential pathways here. If the user has access to the other facility, then they should be able to go in to that facility queue, remove the patient from that queue, and add them back in the correct facility queue. If the user doesn't have access to the other facility, they're just kind of stuck and won't be able to do anything besides reach out to the other facility and ask them to remove the patient from their queue.

I will say that AFAIK, we've never had user reports of this issue; this has purely been something that devs have discovered when messing around in testing environments. So I don't think it's terribly common in the real world, but we want a better scenario than just throwing them to the 400 page.

**Comment by Rebecca-LM** [comment]
@emmastephenson thanks for the context. In that case I suggest this:

"This person is already registered at [facility name]. To test them at your facility, you'll need to remove them from the other facility and add them to yours. If needed, contact [facility name] directly to resolve this issue."

**Comment by emmastephenson** [comment]
Thanks @Rebecca-LM! I guess my one concern there is that this might imply that the patient needs to be taken off the other facility's roster or somehow archived from the facility, but really they just need to be taken off the other facility's queue. (Mostly I worry people will somehow conflate this with self-reg at different facilities, we get questions in support about that frequently). Could the content change to something like "This person is already being tested at [facility name]"?

**Comment by Rebecca-LM** [comment]
@emmastephenson ah, that makes sense. Can you explain what it means to be on their queue vs. just in their system or registered there?

**Comment by emmastephenson** [comment]
Sure! Being registered at the facility just means you're in their list of patients. Being queued at the facility means that you have a test result pending submission, so somebody has started conducting/recording a test for you but hasn't submitted it yet for some reason.

In this example, this is the queue at Facility 1 (Central Middle School):
<img width="1054" alt="Screen Shot 2021-12-21 at 11 48 01 AM" src="https://user-images.githubusercontent.com/80282552/146989087-a09ef796-80e8-4b0d-85a9-59b314311dab.png">

And this is the person list for Central Middle School:
<img width="987" alt="Screen Shot 2021-12-21 at 11 48 35 AM" src="https://user-images.githubusercontent.com/80282552/146989157-de68dfdc-0652-470c-b5f6-8c36073e3897.png">

There's a second facility in the same org, "this facility is bogus". "Emma TestAccount" is registered at both facilities, meaning that patient appears in both facility lists. This is the patient registration list for that facility:
<img width="992" alt="Screen Shot 2021-12-21 at 11 48 27 AM" src="https://user-images.githubusercontent.com/80282552/146989291-980eba7e-0412-4a1c-abf0-2a560290e811.png">

If I tried to add "Emma TestAccount" to the testing queue at "this facility is bogus", that's when I'd run into this 400 error, because that patient is already in the middle of a test at the first facility, "Central Middle School." It's fine for the person to be registered to both facilities, it's only when they're trying to conduct simultaneous tests on the same person that we run into problems. Does that make sense?

**Comment by Rebecca-LM** [comment]
@emmastephenson ok that makes more sense. Can they just be removed or deleted, or what are the options since they're in pending status? I took a guess below -- remove or submit?

"This person has a pending test in the queue at [facility name]. To test them at your facility, you'll need to first remove their test from the other queue, or submit the test. If needed, contact [facility name] directly for help with this issue."

**Comment by emmastephenson** [comment]
Yep, the options in this case are to remove or submit the pending test. The new copy looks perfect, thank you!

**Comment by LGFranklin** [comment]
Ready to start engineering work on this.

**Comment by kenieh** [comment]
relevant slack thread: https://skylight-hq.slack.com/archives/C01SJ0DUL7N/p1649172932681069

**Comment by emmastephenson** [comment]
Closing as we haven't seen this in the wild - will re-open if it becomes an issue
