### ISSUE TITLE
SPIKE: Handle number of instances between stg and prod better during deploys

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3136]
### Why are we doing this?
On 12/17, we increased the total number of app instances to 5 to combat intermittent database issues. (This turned out not to be the fix, but that's besides the point here.) On a rollout to production, the number of instances effectively doubles because the prod.stg slot also spins up 5 new instances. This overwhelmed our available database connections (480 at current levels; 50 connections per instance * 10 instances = 500 attempted connections) and new database connections were rejected, causing a slew of pages.

### Action requested
This is a spike to investigate how to make sure we're managing instances/database connections on rollout effectively. Could we:
- reduce the number of connections available per instance on deploy?
- spin up fewer stg instances?
- some other clever solution?

### Additional context
See threads in the engineering channel: https://skylight-hq.slack.com/archives/C01LTSNKEPP/p1640046787098500
https://skylight-hq.slack.com/archives/C01LTSNKEPP/p1639782836086200
https://skylight-hq.slack.com/archives/C01LTSNKEPP/p1639778581067500

**Comment by emmastephenson** [comment]
@jdorothy to do some investigation on this before 1/6 eng sync.

**Comment by LGFranklin** [comment]
Prep work before engineering sync then will determine waht to do about it.

**Comment by jdorothy** [comment]
We don’t have any control over the slots, meaning we can’t do rolling deploys - we get everything at once. We do have some options around connection pooling / performance, though. In #2635, we investigated reducing our connection pool sizes and optimizing the pool for better concurrency (based on spike findings from #2181). That didn’t quite work the way we had hoped and now we’re at a point where we’ve scaled App Services to ~500 total connections. 

Some background: The connection pool issue was actually a performance issue flagged by Azure. The recommended solution was to use pgBouncer, but that required us to manage our own VM and it wasn’t a burden we wanted to take on if we could avoid it. But Azure Flexible Servers are now in general availability, and one big benefit they provide is pgBouncer as a managed service. We talked the following pros/cons over at 1/6 engineering sync and agreed that this is a good step to take towards better handling future scaling.

Some tidbits I learned:
- Postgres servers have regular planned maintenance windows. But - you don’t get to pick that time, and so your DB will eventually be randomly restarted, resulting in 60-120s of downtime. That might explain a few “blips” we’ve seen from the DB in the past.
- Why weren’t we using this from the start? We do have one instance in stg from way back, possibly from an unrecorded spike. My guess is that it was due to being in preview - Terraform support (9/21) and general availability (11/21) were pretty recent.

Pros/cons vs. standard:

Pros:
- Zone redundancy
- Also zone redundant backups
- You can choose maintenance window
- 16TB storage vs. 1 TB
- Stop/start support
- Private DNS zone support
- SSL enforced
- pgBouncer built in

Cons:
- No read replicas
- No advanced threat protection (auto-enabled on standard)
- No geo-redundant backups/replicas (we don’t use this feature on standard, local region backups only)
- No intelligent performance (auto-enabled on standard)
- No storage auto-grow

Conclusion: make a ticket to capture this work and prioritize it. #3180
