### ISSUE TITLE
Update Isolation Guidance Included When Test Results Are Available

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-simplereport#3199]
Under the section "What does my result means?", the isolation guidance needs to be updated to reflect the shorter isolation guidance CDC announced at the end of December. Thanks!

cc- @LGFranklin @tim-skylight

**Comment by Rebecca-LM** [comment]
From Slack thread by Leslie:

Tim, Tim and I spoke about this last week at our sync. @tim-skylight  was going to have the BetterData team make a change that would be more enduring since the guidance changes. We also got a note from MT last week asking if we were updating it and requesting that it say something like "check with your local dept for any localized guidance" bc they were still recommending 10 days given the limited masking in their communities. This is on Tim's team's list, but I know they've been prioritizing the work around results right now.

**Comment by mlighdc** [comment]
Know you all are working hard on the expired link issue. Any estimates on when the guidance will be updated? Just trying to get an estimate as we are getting more feedback that our guidance is out of date. Thanks!

**Comment by Rebecca-LM** [comment]
@mlighdc this ticket is covered by https://github.com/CDCgov/prime-simplereport/pull/3223#issuecomment-1012294764 so I will close it out. We're working on it now.
