### ISSUE TITLE
Create count table for test events

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3249]
### Background
Some of our longer sql queries are the get counts that are required to calculate on each view of the results page. Adding a new table to track these specifically instead of an inner join would vastly speed up response times.

### Proposed solution 
Create a new table that stores counts of test events by facility, and rework the getTestCount graphQL query to use it.
When new tests are added, we'll need to add them as test events associated with the facility and also increase the count on this table.

**Comment by emmastephenson** [comment]
Could definitely be an index table on facility id instead

**Comment by nickclyde** [comment]
Did a bunch of research into improving the test count query. Kind of hitting a wall there because the query takes filters (we're not just counting by facility but also filtering by patient, date etc). So making a count table/matview would only be useful per filter - ie we would need have a count by facility table, and a count by patient/facility table, and so on... I'm not sure it's worth setting up count tables by every conceivable filter combo. And we already have indices on the columns that make sense (facility and patient id). Any thoughts?
