### ISSUE TITLE
Clean up end-user facing test result displays

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#3469]
![image.png](https://images.zenhubusercontent.com/6196b08a969160bed8994a93/2831e1c6-bb2e-4d20-a68f-c5af9b9ab386)

- Currently we display test device model (the "test device" field above), which is a ReportStream compatibility thing/shouldn't be in end user reports. This field should be removed
- We don't include the test device type (Antigen, RT-PCR, etc) in any end-user facing content, which is commonly requested/needed. 
- In the short term, device addition requests are asked to include it in the input text field/device name. For this ticket, we should go through out devices and make sure the test type is consistent/included in the name, but long term, we'd probably want this to be a separate column in the table as outlined in [this ticket](https://github.com/CDCgov/prime-simplereport/issues/3470)

**Comment by tim-skylight** [comment]
@fzhao99 I think there is some use case for keeping both names in there, as it gives us a common, human readable name for the device as well as a precise name that maps back to a CDC generated spreadsheet. This could help in the future in case there is confusion over what test was administered. Also, the TYPE of test (antigen, pcr, etc) does display on the results because we use the test name with the test type appended in parentheses. I think we should close this story and instead pick up 3470 and then display that new field in the results. Thoughts?

**Comment by fzhao99** [comment]
Understand your point about having something human readable and the precise name that maps back to the LIVD sheet, but I think the rationale behind this ticket was that since these specific reports are end-user facing, it's not useful to them the precise CDC label we put on their tests (ie the test device name), which is why we thought we could remove it. Fwiw, if there was any confusion, we could run a Metabase query to get the mapping back to the LIVD model name. Paging @Rebecca-LM who I think was there in that meeting

Totally agree that some of this is obviated by #3470 and that we can just display that either as a separate field or as an addendum to the name itself. Would defer to Rebecca on which one is better.
