### ISSUE TITLE
Update copy for printable multiplex patient results

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3493]
### Background
Update printable patient results to include Multiplex information.

### Design

**FIGMA: https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=6991%3A25519**

**POSITIVE FLU + COVID RESULT**
![Screen Shot 2022-05-02 at 1.17.08 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/3a82f962-e028-4b12-b218-744c3b7975ba)

**POSITIVE FLU ONLY**
![Screen Shot 2022-05-02 at 1.17.18 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/619112fc-fd5d-44f3-a6a2-3df87904ebe6)

**NEGATIVE ALL**
![Screen Shot 2022-05-02 at 1.17.13 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/d0879f95-25f4-4d73-aa31-92bf5ef14360)

**SPACING SPEC**
![Screen Shot 2022-05-02 at 1.17.27 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/4f809af9-037e-4726-9bda-7ba2a265eea2)

### Acceptance Criteria

- [ ] Add flu a result
- [ ] Add flu b result
- [ ] Add "(+)" or "(-)" next to COVID-19 and flu results. This is further help to distinguish between "Positive" and "Negative"
- [ ] Rename document header to be "Test results: COVID-19 and flu"
- [ ] Rename "Notes" header to be "More information"
- [ ] Update "notes" guidance based on positive or negative results for COVID/Flu
- [ ] Add space in between test details and test results
- [ ] When a patient has both a positive COVID and positive flu result, add "COVID-19 guidance" and "Flu guidance" to the "More information" section to distinguish both sections. Also add space between both sections.

### Additional context

**Reach out to Kenny for clarification on the copy for the "More information" section**

**"More information" copy for POSITIVE flu result:**
Most people with flu have mild illness and can recover at home. Stay at home and avoid contact with others until at least 24 hours after your fever is gone, except to get medical care or other necessities. Wear a face mask if you leave home, or cover coughs and sneezes with a tissue. Wash your hands often.

[People at Higher Risk of Developing Flu–Related Complications](cdc.gov/flu/highrisk) (cdc.gov/flu/highrisk) should contact a doctor as soon as possible to see if antiviral treatment is recommended.

For more information, visit [Flu: What To Do If You Get Sick](cdc.gov/flu/treatment/takingcare.htm) (cdc.gov/flu/treatment/takingcare.htm).

Spanish translations: 
[https://app.zenhub.com/files/302387839/7377ceed-6d15-4780-9402-436c668590b7/download](https://app.zenhub.com/files/302387839/7377ceed-6d15-4780-9402-436c668590b7/download)

**Comment by emmastephenson** [comment]
@kenieh can you update screenshots?

**Comment by kenieh** [comment]
@emmastephenson updated!

**Comment by emmastephenson** [comment]
@emyl3 Adding some additional context below!

I _think_ but am not positive that the content for this component is shared between the printed PDF view of results and the text view (#3494). They both seem to use the [`TestResults`](https://github.com/CDCgov/prime-simplereport/blob/8b6da5d70c5972bf60ca19e7663a609f2cbc838c/frontend/src/patientApp/timeOfTest/TestResult.tsx#L133-L133) component as the source of truth. That in turn relies on [`en.ts`](https://github.com/CDCgov/prime-simplereport/blob/8b6da5d70c5972bf60ca19e7663a609f2cbc838c/frontend/src/lang/en.ts#L240-L241) and [`es.ts`](https://github.com/CDCgov/prime-simplereport/blob/8b6da5d70c5972bf60ca19e7663a609f2cbc838c/frontend/src/lang/es.ts#L250-L250) for the actual content.

The specific asks for this ticket are:
* Update en.ts and es.ts with the new "Flu Notes" content at the top of this ticket. 
* Add conditional logic in `TestResult.tsx` that only shows the flu content if the result of the query to fetch results includes multiplex results. You'll need to work with @nickclyde to coordinate this, since we're not actually calling the query anywhere yet 😄 You'll probably need to change the props for [`TestResultNotes`](https://github.com/CDCgov/prime-simplereport/blob/8b6da5d70c5972bf60ca19e7663a609f2cbc838c/frontend/src/patientApp/timeOfTest/TestResult.tsx#L56-L70) to include a check for "isMultiplex" or similar.
* The content/conditional showing will need to be changed in both the Notes function and the header of the page.
* Validate that the new copy shows up when printing a multiplex result but does NOT show up when printing a covid-only result.
* Check to see if it also shows up on the patient experience, because we might also get to knock out #3494 with the same work! 😄 

Happy to pair on this; it's a little more complex than I remembered!
