### ISSUE TITLE
SPIKE: Create metabase queries of contact list for multiplex device users

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3605]
- Gather the list of affected orgs in metabase
- Somehow combine that list with Okta for contact info?

**Comment by emmastephenson** [comment]
Here is a quick stab at this table: https://prime-simple-report-prod-metabase.azurewebsites.net/question/412-top-multiplex-facilities

It gives us all facilities doing testing with a multiplex device, but:
- there might be duplicates if a facility is using multiple multiplex devices, because this groups by device_specimen_type
- Not all attached facilities have emails
- It only uses the 4 devices that are currently listed in our database as multiplex, there might be more
- This gives us facility contact information, which isn't the same as admin contact information. But to get the latter we would need to go through Okta

**Comment by emmastephenson** [comment]
I also created a table showing the SimpleReport users who have ever recorded a multiplex test event: https://prime-simple-report-prod-metabase.azurewebsites.net/question/414-multiplex-users

This has the benefit of including all users who have ever recorded on multiplex, but:
- Again, this doesn't give us information about admin info - we'd need to go through Okta for that
- We might be contacting multiple users from the same facility or organization

**Comment by emmastephenson** [comment]
Notes on the cardinality of the above: we have around 550 facilities to notify, 350 orgs, and 1200 end api users.

**Comment by emmastephenson** [comment]
@jayna-SkylightDigital are the above dashboards sufficient, or do we need more to reach out to users?
