### ISSUE TITLE
SR map state names

### ISSUE THREAD

**Issue by Rebecca-LM** [CDCgov/prime-simplereport#3618]
Adding flyovers with state names to SR home page map could might make the map more useful... and more accessible.

Discuss.

**Comment by fzhao99** [comment]
Poked around and found [this post](https://css-tricks.com/svg-map-rollovers/
) on SVG hovering actions. Looks like we just need to add some javascript to bold/highlight the relevant pieces on the svg itself, which is totally doable, and if we wanted to display tooltips rather than the way the post is doing it, that'd be fine too.  

The thing I'm considering is that for use cases in which people are curious about whether SR is live/coming soon in their state, those users would probably be able to pick out where/whether their state is on the map and therefore the SR pipeline pretty quickly. Totally agree that it would improve accessibility for folks who are looking at SR availability country wide and in general to break things out by state (so may be worth it to do this just for that reason), but I think the marginal impact on the person who is wondering whether SR is live in their state isn't that high. But defer to the designers/ and @jayna-SkylightDigital about value in the net.

**Comment by emmastephenson** [comment]
@nickbristow will ping you offline, but hoping you can weigh in on the accessibility considerations here.
