### ISSUE TITLE
SonarCloud coverage incorrect 

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3778]
### Background
A couple PRs have appeared recently where the code coverage is extremely and inaccurately low (#3750, #3682). These were cases where the test coverage was actually pretty good and the accurate test coverage was reflected locally, but wasn't being picked up once the changes were pushed for review. 

### Action requested
Investigate and see if something has recently changed to make SonarCloud ignore tests that have been written.

### Acceptance Criteria
SonarCloud coverage is accurate again

**Comment by emmastephenson** [comment]
@johanna-skylight @nickclyde do y'all have any details to add here?

**Comment by johanna-skylight** [comment]
Adding more details below around my specific situation with #3750 in case it can help to identify the issue.

I ran the jacoco report locally and was able to verify that the coverage was over 90%.
Test coverage was added to existing test files and still the new coverage was not picked up.
New test files were also not picked up.
The backend test job ran successfully for the PR.
Code smells fixes were successfully picked up by sonar cloud... so not sure why the issue is only happening for test coverage.

**Comment by nickclyde** [comment]
For #3682, you can see that [this commit reported](https://github.com/CDCgov/prime-simplereport/runs/6413545568) 87.8% coverage, however the [following commit](https://github.com/CDCgov/prime-simplereport/runs/6415055847), which changed no test code, reported 27.9% coverage. The second run reported that TestOrderService.java had no test coverage at all, which is obviously wrong - it has been at least partially covered by tests for a long time!
