### ISSUE TITLE
Data Entered by Users needs Data Validation

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#380]
_As a human doing data entry I want to get feedback if I'm trying to enter or submit invalid data so that I submit data correctly the first time and it's harder for me to make mistakes._

Design guidance:
- Use USWDS error highlighting styles where available. Note: USWDS appears to have this for inputs but not radios/checkboxes/dropdowns. We will need this style also for instances where a required field is left blank.
- Implement this styling when a user tries to click save but is missing a required field, has an improper data format, or any other error.
- When user tries to submit without filling out a required field, the helpful error message should say: "This is a required field"
- When user tries to submit with improper data format (e.g. for zip code), the error message should provide instructions indicating the correct format, e.g. "Zip code must be 5 digits".
- When user tries to leave with unsaved changes, they should get the "unsaved changes" warning.

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/345e5c02-2db8-4486-a78a-732ee83c45e1)

**Comment by dmethvin-gov** [comment]
This is blocked by #347, which requires either updating our custom components or moving to Trussworks.

**Comment by timothybest-usds** [comment]
Lets incrementally move to Trussworks. I would imagine as we need a new componet feature we would refactor the existing `commonComponent` to point to the Trusswork component

**Comment by willusds** [comment]
@dmethvin-gov are you working on this?

**Comment by dmethvin-gov** [comment]
Looks like this is at least a partial dup of #311 which I had grabbed for a PR. That ticket was closed so I'll update the PR to mention #380.

**Comment by katiealoisi** [comment]
The Skylight team is also working on form validation and error handling for the patient app ([#709](https://github.com/CDCgov/prime-simplereport/issues/709)). Since the patient app and core SR app are using the same core form component, adding error handling in the patient app will also extend to the patient profile form in the core app.

Since they are covering everything related to the patient form (add/edit patient, TOT questions), this ticket will focus just on form validation and error handling for anything related to facility settings.

Design guidance:
- Use USWDS error highlighting styles where available. Note: USWDS appears to have this for inputs but not radios/checkboxes/dropdowns. We will need this style also for instances where a required field is left blank.
- Implement this styling when a user tries to click save but is missing a required field, has an improper data format, or any other error.
- When user tries to submit without filling out a required field, the helpful error message should say: "This is a required field"

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/345e5c02-2db8-4486-a78a-732ee83c45e1)

**Comment by aliciabeckett-gov** [comment]
This has been completed.
