### ISSUE TITLE
Adjust Twilio alerts to exclude landline errors

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3817]
### Background
With the recent [changes to add paging](https://github.com/CDCgov/prime-simplereport/pull/3671) for Twilio alerts, we started surfacing many landline errors. This prompted us to handle these errors in-app, which is complete with #3750. However, we'll continue to be paged for these errors as most are caused by user error.

### Action requested
Is it possible to tweak the Twilio alert to ignore landline errors (#30007s)? Now that we're handing them appropriately, these specific errors are a no-op for the oncall engineer.

### Acceptance Criteria
Twilio alert still fires, just not for landline errors.

**Comment by alismx** [comment]
I recommend that the 30007 alert for messages filtered stay. The threshold is three, and this alert hasn't fired since May 26th, 2022.

Twilio recommends that we open a support ticket with them if we get 3 of these errors, AND we believe our messages shouldn't be filtered. I believe it could be an early indicator of a major problem with our message sends. This error points out these possible problems. https://www.twilio.com/docs/api/errors/30007
- Your message was identified as spam or unwanted messaging by Twilio's message filtering system
- Your message was flagged as objectionable and blocked by a wireless carrier

--

I'm leaning on the side of suggesting we leave the broader Twilio alert intact. This alert includes every possible error Twilio might return to us and has a threshold of 200. The last time this alert fired was on May 26th, 2022, and it appears to be trending downwards for the moment.

On the one hand, it is a catch-all and could signal a severe issue; on the other, most of the errors in this bucket are issues with sending to landlines. I'll include a screenshot of all the errors this has caught since its creation.

Lastly, creating alerts for individual errors could be a significant lift due to how many different errors we could get and how Twilio breaks them up for us to catch. Here is the list of possible errors: https://www.twilio.com/docs/api/errors

![Screenshot from 2022-06-22 11-06-50](https://user-images.githubusercontent.com/94012653/175110216-3a69caeb-f0d2-49c6-b7a2-b35074ea1365.png)

@emmastephenson @rin-skylight Thoughts?

**Comment by emmastephenson** [comment]
@alismx my bad, I meant to say we should filter out 30006, for the landline exceptions! I definitely agree, we want to keep errors with a code of 30007. That was the underlying cause of our AT&T issues a few months ago, and can fail very quietly, so I 100% want to continue alerting on that.

I also agree that we can leave the alert as-is for now. I was worried about the noisyness of this alert given that we had a lot of landline warnings at the time, but like you said this alert has been quiet for a few weeks so it's not as much of a concern now. I'm fine with closing this ticket for now and reopening if we need to fine tune the Twilio alerts down the line.

**Comment by alismx** [comment]
I'll close this for now.
