### ISSUE TITLE
First login experience for CSV upload users

### ISSUE THREAD

**Issue by vz3** [CDCgov/prime-simplereport#4023]
Add copy to the first login screen ("Welcome to SimpleReport!") to make it more clear for CSV upload users. 

#1: (below required fields text) 
Please enter one facility to get started. You can add more after account setup.

If you plan to upload your results in bulk, you can include additional facilities in your spreadsheets without adding them in SimpleReport.

#2: (below line)
Please enter one ordering provider to get started. If you need to, you can add more after account setup.

If you plan to upload your results in bulk, you can include additional ordering providers in your spreadsheets without adding them to SimpleReport.

#3: (below line) 
If you don't see a device you're using, please contact support@simplereport.gov, and request to add a new one.

If you plan to upload your results in bulk, enter one device here to get started. You can include any additional devices in your spreadsheets without adding them here.

![Current w callouts.png](https://images.zenhubusercontent.com/57322f73bf93871ccd9ad030/fcdefe39-be7c-40c2-aefc-6ed29283c20d)

**Comment by charlye-skylight** [comment]
@emmastephenson what are fields are required on this form?

**Comment by emmastephenson** [comment]
Required right now is:
- Testing facility name
- Testing facility phone number
- Testing facility address (street address, state, and zip)
- Facility CLIA number
- Ordering provider first/last name
- Ordering provider NPI
- Ordering provider phone

I think the form also requires you to select a default device before moving forward.

**Comment by vz3** [comment]
(Added current state w # callouts to description)

**Comment by vz3** [comment]
Here's a quick/rough starting place for @lauraykerr . The numbered callouts are approximately where the copy would be placed. Happy to add additional callouts if needed.

#1:
You'll be able to add additional facilities after you submit this form.

Note for bulk results users: Please enter a single facility that you plan to submit results for. When you're creating a bulk upload, you will be able to enter the information for any facility.

#2:
If you have multiple ordering providers, you’ll be able to add more ordering providers once your account has been created.

Note for bulk results users: please enter one ordering provider in this form, and you'll be able to enter ordering providers in the spreadsheet. 

#3:
Note for bulk results users: You can enter one device you'll be using for testing, and when you're creating your spreadsheet, you'll be able to enter whichever device you've used for each test you report.

**Comment by lauraykerr** [comment]
@vz3 Some suggested text is below. Some general thoughts and considerations: 

- Changed the "note for bulk results users" because am assuming not all users will know if they are at this point, but can revisit if that's not the case
- Tried to address "enter one [ ] to get started" to all users, since that applies across the board
- Wonder if we want to switch around some of the text at the top of the form — we could keep "Required fields are marked..." where it is (1), remove the note "To get started...," and place #1 text underneath "Testing Facility Information" (will illustrate in another comment)

**Suggested text**

#1:
Please enter one facility to get started. You can add more after account setup. 

If you plan to upload your results in bulk, you can include additional facilities in your spreadsheets without adding them in SimpleReport. 

#2:

Please enter one ordering provider to get started. If you need to, you can add more after account setup.

If you plan to upload your results in bulk, you can include additional ordering providers in your spreadsheets without adding them to SimpleReport. 

#3:
If you don't see a device you're using, please contact support@simplereport.gov, and request to add a new one. 

If you plan to upload your results in bulk, enter one device here to get started. You can include any additional devices in your spreadsheets without adding them here.

**Comment by lauraykerr** [comment]
Suggestions for top of form:

## Welcome to SimpleReport!
Required fields are marked with an asterisk (*).

### Testing facility information
Please enter one facility to get started. You can add more after account setup.

If you plan to upload your results in bulk, you can include additional facilities in your spreadsheets without adding them in SimpleReport.

**Comment by lauraykerr** [comment]
Suggestions for top of form:

## Welcome to SimpleReport!
Required fields are marked with an asterisk (*).

### Testing facility information
Please enter one facility to get started. You can add more after account setup.

If you plan to upload your results in bulk, you can include additional facilities in your spreadsheets without adding them in SimpleReport.

**Comment by nathancrtr** [comment]
@vz3 quick styling question: do we want the additional help text to be full-width or narrower (see pics)?

![Screen Shot 2022-10-11 at 11.56.01 AM.png](https://images.zenhubusercontent.com/604fb43ab2c0ce6f2a47191e/9697f6db-1d5f-4178-9b8f-9a884e94d667)

![Screen Shot 2022-10-11 at 11.55.55 AM.png](https://images.zenhubusercontent.com/604fb43ab2c0ce6f2a47191e/9c2590a9-1181-4dec-87e3-560791971aac)

**Comment by vz3** [comment]
@nathancrtr narrower pls!
