### ISSUE TITLE
Resolve slowdown in database queries during production deploy

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#4064]
## Description

We experienced a slowdown in database query performance during a production deploy. This does _not_ appear to be related to https://github.com/CDCgov/prime-simplereport/issues/3953, which may cause similar behavior under similar scenarios.

https://skylight-hq.slack.com/archives/C01LTSNKEPP/p1658779542717329?thread_ts=1658775228.966189&cid=C01LTSNKEPP

https://skylight-hq.slack.com/archives/C01LTSNKEPP/p1659122036670229?thread_ts=1659120024.510939&cid=C01LTSNKEPP

## Acceptance criteria
* ?

## Dev approach
* Look into how the way our staging slot suddenly creates new resources on deploy
    * Before we changed over to the flexible database, the stg slot would copy all of the prod slot's infrastructure (each version adding additional active connections)
    * This would tip us over our connection limit and cause issues
    * This _shouldn't_ be happening now with ~5000 connections available, but this is a potential avenue of research
* Maybe an issue with our CI/CD pipeline slowing down queries during deployments?
    * Could be running up against the limit of database connections which is then overwhelmed by the rollout
* Logs indicate a very large quantity of audit-related database queries in progress at the time of the deploy
    * Maybe the container was killed before all of them could complete + close?

**Comment by emmastephenson** [comment]
I'm upping the priority of this issue, as it was just seen during another production deployment on 8/2 (the deploy happened around 1:07PT and the slowdown occurred at 1:15PT.)

**Comment by alismx** [comment]
This was very difficult to investigate. The best I've been able to glean is that it happens when multiple deployments are triggered close to each other. We need more information.

My recommendation at this point is that we enable some additional tools to help future investigations.
1. Enable a long query log: Set the Postgres configuration with something like this `log_min_duration_statement = 2000`
2. It might be worth enabling `auto_explain`, which we can use to find unstable execution plans.
3. Enable `pg_stat_statements`. We can use this to find the queries that add the most load. Long-running queries are a problem, but efficient queries we run often can also add substantial load. We can use information from this to find out how much total execution time the database spends on all our queries.

**Comment by alismx** [comment]
@rin-skylight Would you prefer to keep going with this ticket or should I write up a new ticket to explore the recommendations I made?

**Comment by rin-skylight** [comment]
From what we gathered, it seems like this error pops up when we have a third slot active, as each slot, even when receiving no traffic, spawns the requisite data connections. Deleting the extra slot (used for spring upgrades) seems to have resolved these issues.

Let's write up the other tickets, for the sake of helping future us! They can be lower-priority.
