### ISSUE TITLE
Make device selector on support UI a combobox

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4124]
### Background
We have enough devices that finding one with the selector tool is tricky. Changing to a combobox (like the organization search) would be better.

### Action requested
Change the device dropdown in the "edit/add device" _internal_ superuser admin UI to a combobox. (Not the facility form, though we should probably also reevaluate that one)

### Acceptance Criteria
Internal device edit page uses a combobox

**Comment by emmastephenson** [comment]
Update: the ask is to change the device selector to a combobox application-wide (i.e. also in the facility settings page.)

**Comment by georgehager** [comment]
@emmastephenson Just want to confirm, the places that should now be a combo box are in 2 places, the facilities management page for admins and the edit device page for superadmins:

![Screen Shot 2022-09-08 at 2 04 57 PM](https://user-images.githubusercontent.com/89797785/189195158-48e98f24-1895-41c4-aeb2-76bc94d10e7b.png)
![Screen Shot 2022-09-08 at 2 06 43 PM](https://user-images.githubusercontent.com/89797785/189195160-12c30bce-3e38-4183-9bd2-7945fe5eac51.png)

**Comment by emmastephenson** [comment]
Apologies for the delayed reply; can confirm that those are the two components that need to be updated!

**Comment by georgehager** [comment]
After discussing with @kenieh, we are going to hold off on refactoring the Manage Devices section on the Manage Facilities page (for org admins). We need some user validation before changing the design.

I suggest we move away from the initial idea of using combo boxes in the Manage Device section due to the complexity of implementing local state to properly handle multiple devices, addition, and deletion. Instead, we can use the MultiSelect component that already exists in SimpleReport. This component was built out based on combobox, and is used on the "Edit existing testing device" page (in the super admin view) for selecting SNOMED Code and Supported Diseases. It would look like this:
![Screen Shot 2022-09-12 at 3 23 03 PM](https://user-images.githubusercontent.com/89797785/189739426-2cad46dd-29a5-4d7a-94ae-03ed59648d1c.png)

See a video of the application here:
https://user-images.githubusercontent.com/89797785/189739508-66419858-a3a3-435c-8080-9463ecd688cb.mov

Code changes for this implementation are on branch `george/4124-device-selection`.

We'll proceed with refactoring to use a combobox on the "Edit existing testing device" page (in the super admin view), and will spin out a new ticket for this suggested change

cc: @emmastephenson

**Comment by emmastephenson** [comment]
Thank you for the detailed update George! I'll save questions on the Manage Facilities page for the new ticket :)

**Comment by georgehager** [comment]
[New ticket](https://github.com/CDCgov/prime-simplereport/issues/4269) for org admin page
