### ISSUE TITLE
LGTM.com will be shut down in December 2022

### ISSUE THREAD

**Issue by snesm** [CDCgov/prime-simplereport#4224]
LGTM is approaching [End of Life](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/).  New commits will no longer be analyzed by the end of Nov 2022.

CodeQL should be enabled to [replace](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository) LGTM.

**Comment by emmastephenson** [comment]
Looks like the plan is that the LGTM team will open up a PR on our repo to add a GH action to enable CodeQL instead of LGTM. [Source](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/#:~:text=For%20those%20repositories%2C%20we%20will%20create%20pull%20requests%20that%20add%20a%20GitHub%20Actions%20workflow%20that%20runs%20code%20scanning)

**Comment by snesm** [comment]
That's what "should" happen.  SimpleReport can wait to see it that works, or correct it ahead of time.

**Comment by rin-skylight** [comment]
This migration is complete!
