### ISSUE TITLE
Embed updated onboarding video to spreadsheet guide

### ISSUE THREAD

**Issue by charlye-skylight** [CDCgov/prime-simplereport#4253]
The onboarding video for the spreadsheet uploader needs to be embedded on the guide page.

- Will be hosted on SR's YouTube channel

## Placement of video: 

![image.png](https://images.zenhubusercontent.com/608048cb755ce5a91e249492/8c2dd199-49a8-469d-aa8b-2af9982b7c54)

**Comment by lauraykerr** [comment]
The updated video is on the Drive: https://drive.google.com/file/d/1qR4SxUypedS43oLx2gXxAEPH8U_qU4Fh/view?usp=sharing

@vz3 Did you want to pair on placement of the embed or are you set?

**Comment by vz3** [comment]
@lauraykerr The pink area in the screenshot is where we're thinking, but lmk if you have other thoughts

**Comment by vz3** [comment]
@zdeveloper @lg-king To re-raise the YouTube question, I continue to think that YouTube will save us a lot of effort versus a hard embed because it offers multiple streaming qualities based upon bandwidth and device. A straight embed would mean we'd have to identify a fixed resolution and compression for this video, which as formatted is 316mb. We can compress to a lower quality, but that of course means we're not serving our higher bandwidth users in ideal fashion. I propose that if we are unable to upload to CDC or to USDS YouTube accounts, that we create a SimpleReport YouTube that we upload this to for now.

**Comment by lg-king** [comment]
@vz3 I'm all for hosting it on YouTube but not sure if we have to go through any approval process to set up our own YouTube account? I know there would be more involved for us to post it on CDC's YouTube.

**Comment by lg-king** [comment]
Update: I reached out to Mike to see if us hosting it on our own YouTube account is an option.

**Comment by lg-king** [comment]
Mike asked: 
Would another alternative be to host the video on our server at the current resolution and just expect a higher than average storage and compute cost on our web domain until we sort out the usage of CDC's YouTube? Or is there a hard limit on storage that may be difficult to get around?

**Comment by lg-king** [comment]
Update #2: Reached out to Holly and she prefers the YouTube option :) 

FYI: 

> I like your idea of a SimpleReport YouTube channel as an interim solution. Having a better quality video with a transcript is definitely my preference. And, this approach aligns with the guidance from Dana as I understood it.

**Comment by lauraykerr** [comment]
Link to the video on the SimpleReport Youtube channel: https://www.youtube.com/watch?v=qqhC7PFBdek

@vz3 @lg-king @zdeveloper
