### ISSUE TITLE
Delineate spreadsheet upload experience from regular SR flow (Research and design)

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4290]
We have not validated that there is a user need to integrate bulk uploaded results with individually entered results. 

- Terminology for "conduct test mode" vs. "upload spreadsheet mode" 
- How does a user switch between modes? (explore icon/text treatment, e.g., Zenhub switch workspace). What helper text might we want to provide?
- How can a user select a default mode? Do we default certain types of orgs to a specific mode?
- How do we introduce both modes upon registration/first login? (i.e., what is the first login experience?) Does having 2 modes impact this experience?
- Navigation language

**Comment by vz3** [comment]
Questions coming out of convo w @lauraykerr:
- what do we call the two modes?
- should we use a toggle that displays both labels?
![image.png](https://images.zenhubusercontent.com/57322f73bf93871ccd9ad030/b8eaa76b-ec1c-4aab-9de1-06728a7fc0bc)
- should we use a Zenhub-style toggle button?
if so, what happens when the user clicks that button? do they immediately switch? do we present a modal?
