### ISSUE TITLE
Update bulk results upload guide (copy changes) 

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4404]
Update guide to incorporate the latest suggestions in this doc: https://docs.google.com/document/d/1EIZvjLOx3PIPA5w1B1oeBKBgqiHRJnMSsLIQHBLysjo/edit?usp=sharing

Changes: 
- [ ] Update link names under resources (p1)
- [ ] Updating data element name to "Ordering provider" (p2) 
- [ ] Updating instructions and linking to device code lookup tool under Equipment model name (p8), Test performed LOINC code(p9), Test result (p10), Specimen type (p12)

**Comment by vz3** [comment]
Updated comps here:
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=13176%3A34612

**Comment by vz3** [comment]
(Ah just realized the "Device lookup" code here was a placeholder, I don't know that we settled on a name? cc @lauraykerr

**Comment by vz3** [comment]
also need feedback on my "no matches found" copy which can be seen here:
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=13176%3A34615

**Comment by lauraykerr** [comment]
For tool name, if we're sticking with "[verb] + [function]" for tabs (e.g. "View test results"), what about "Find device codes"?

Throwing this out there, though: I wonder if we want to consider adding the guide as a separate tab instead of the lookup tool, then linking to the lookup through the guide. I think we need to highlight the guide more in general, and I don't know that users can use the tool without going through guidance first. 

Thoughts? @vz3 @lg-king

**Comment by lauraykerr** [comment]
Added suggestions for integrating the device code lookup tool into the guide in the [latest iteration of the guide doc](https://docs.google.com/document/d/1EIZvjLOx3PIPA5w1B1oeBKBgqiHRJnMSsLIQHBLysjo/edit?usp=sharing)
