### ISSUE TITLE
Newly created organizations are non-functional

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#450]
- [ ] The `createOrganization()` mutation should also create an initial Facility for the organization with the same  required fields as `addFacility` and `updateFacility`
- [ ] add a `/admin` route to the URL with a form for creating an Organization
---

If I create a new organization using the admin console, then log in on the client that organization, the client errors out because it assumes that there is at least one live facility, and there isn't (because I was expecting to create the first one through the UI).

This can likely be reproduced by archiving all the existing facilities.

**Comment by aliciabeckett-gov** [comment]
@benwarfield-usds can we fix this by creating a default facility for the organization?

**Comment by benwarfield-usds** [comment]
We definitely could—or we could require that the initial facility information be part of the organization-creation call, so that we're not putting in dummy information that has to be later on. I'd say we should probably have a better error message for the error case regardless, but that's probably not a very high priority if we eliminate the possibility of it showing up in the onboarding process.

**Comment by aliciabeckett-gov** [comment]
Ideally I'd like to get to a place where the organization does all of the setup on their own, and we're completely removed from the process. That's why I'm into the default org over us creating the info for each org as they come online. 

I'm just worried that requiring the first facility as a part of the creation call will limit us in the future in how we onboard. Maybe it could be optional, and if it's not filled out we create a default facility?

@willusds
