### ISSUE TITLE
Fix max page widths

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4559]
## Description
Pages in the app are all different widths. Change max page width of pages and header to 1200px.

Pair with @vz3 on implementation (especially for pages above 1200px - Results, Patients)

## Acceptance criteria 
- [ ] Dashboard, Conduct tests, Results, People, Settings all have same width (1200px)
- [ ] Header has same width (1200px)

**Comment by lg-king** [comment]
Could explore updating nav design as part of this ticket - https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=948%3A211

**Comment by vz3** [comment]
Pulling up USWDS documentation, it's native breakpoints can be found here:
https://designsystem.digital.gov/utilities/layout-grid/#sass-mixins

That includes 1024px, 1200px, and 1400px. The next piece we need to consider is what viewports our users are using. My last analysis showed that only 20% of our users had a 1200px or larger display, and 8% had a 1400px or larger display. Would like to pair with a dev to run these numbers again because this sounded off to me (this was based on GA for our landing page btw)
![image.png](https://images.zenhubusercontent.com/57322f73bf93871ccd9ad030/8b7b6f7f-cfbf-442b-b420-27e3b1356242)

**Comment by vz3** [comment]
Per convo w @johanna-skylight and I, let's go with 1200px for max-width across the app. The results page is I believe the only page that's currently at 1400, the rest of the pages are already at 1200 or 1024
