### ISSUE TITLE
Investigate @Transactional for saving TestEvents

### ISSUE THREAD

**Issue by georgehager** [CDCgov/prime-simplereport#4642]
### Description
Prod api fails intermittently when saving `TestEvent` to `Result`. Even though valid `TestOrder` and `TestEvent` have been created, when the `Result` gets updated as the `TestEvent` is processed it is missing a `TestEvent` `id`. See failures in [Metabase for failed transactions](https://www.simplereport.gov/metabase/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6NDQsImpvaW5zIjpbeyJmaWVsZHMiOiJhbGwiLCJzb3VyY2UtdGFibGUiOjE3LCJjb25kaXRpb24iOlsiPSIsWyJmaWVsZCIsNDIyLG51bGxdLFsiZmllbGQiLDIxNCx7ImpvaW4tYWxpYXMiOiJUZXN0IE9yZGVyIn1dXSwiYWxpYXMiOiJUZXN0IE9yZGVyIn1dLCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQiLDIxMix7ImpvaW4tYWxpYXMiOiJUZXN0IE9yZGVyIn1dLCJDT01QTEVURUQiXSxbImlzLWVtcHR5IixbImZpZWxkIiw0MTgsbnVsbF1dXSwib3JkZXItYnkiOltbImFzYyIsWyJmaWVsZCIsNDE1LG51bGxdXV19LCJ0eXBlIjoicXVlcnkiLCJkYXRhYmFzZSI6Mn0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==)

### Steps to reproduce
See the [PagerDuty Incident](https://prime-cdc.pagerduty.com/incidents/Q1JAM0M78L79K4) and Metabase above.

### Expected behavior
If a save for `Result` fails, the whole `addMultiplexResult` operation should fail.

### Additional context
While `@Transactional` is added at the class level, the `[addMultiplexMethod](https://github.com/CDCgov/prime-simplereport/blob/118d331cc8415890e457e01b6e81b2e781bce1a2/backend/src/main/java/gov/cdc/usds/simplereport/service/TestOrderService.java#L412-L412)` does not have the `@Transactional` annotation, and it's possible this is causing things to go wrong.

### Action Requested
- Investigate if adding `@Transactional` on the method level will resolve this issue, or find another way for the `addMultiplexResult` method to fail if the call to `saveFinalResults` fails
- Follow up by manually fixing corrupted historical `Result` connections between `TestEvent` and `Result` in the prod database
- Resent affected tests to reportstream

**Comment by georgehager** [comment]
### Description
Prod api fails intermittently when saving `TestEvent` to `Result`. Even though valid `TestOrder` and `TestEvent` have been created, when the `Result` gets updated as the `TestEvent` is processed it is missing a `TestEvent` `id`. See failures in [Metabase for failed transactions](https://www.simplereport.gov/metabase/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6NDQsImpvaW5zIjpbeyJmaWVsZHMiOiJhbGwiLCJzb3VyY2UtdGFibGUiOjE3LCJjb25kaXRpb24iOlsiPSIsWyJmaWVsZCIsNDIyLG51bGxdLFsiZmllbGQiLDIxNCx7ImpvaW4tYWxpYXMiOiJUZXN0IE9yZGVyIn1dXSwiYWxpYXMiOiJUZXN0IE9yZGVyIn1dLCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQiLDIxMix7ImpvaW4tYWxpYXMiOiJUZXN0IE9yZGVyIn1dLCJDT01QTEVURUQiXSxbImlzLWVtcHR5IixbImZpZWxkIiw0MTgsbnVsbF1dXSwib3JkZXItYnkiOltbImFzYyIsWyJmaWVsZCIsNDE1LG51bGxdXV19LCJ0eXBlIjoicXVlcnkiLCJkYXRhYmFzZSI6Mn0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==)

### Steps to reproduce
See the [PagerDuty Incident](https://prime-cdc.pagerduty.com/incidents/Q1JAM0M78L79K4) and Metabase above.

### Expected behavior
If a save for `Result` fails, the whole `addMultiplexResult` operation should fail.

### Additional context
While `@Transactional` is added at the class level, the `[addMultiplexMethod](https://github.com/CDCgov/prime-simplereport/blob/118d331cc8415890e457e01b6e81b2e781bce1a2/backend/src/main/java/gov/cdc/usds/simplereport/service/TestOrderService.java#L412-L412)` does not have the `@Transactional` annotation, and it's possible this is causing things to go wrong.

### Action Requested
- Investigate if adding `@Transactional` on the method level will resolve this issue, or find another way for the `addMultiplexResult` method to fail if the call to `saveFinalResults` fails
- Follow up by manually fixing corrupted historical `Result` connections between `TestEvent` and `Result` in the prod database
- Resent affected tests to reportstream

**Comment by mehansen** [comment]
thoughts on whether this is related to something I've seen recently?
I investigated a [page](https://prime-cdc.pagerduty.com/incidents/Q3QY2TOC3BS336) I got on 10/27 about 5xx errors that all came from our RS exception handler function not being able to save warning responses from RS because of the following:
`ERROR: insert or update on table "report_stream_response" violates foreign key constraint "fk__report_stream_response__test_event" Detail: Key (test_event_internal_id)=(1af32e23-1c6b-4be2-aa67-d04dba36c1c5) is not present in table "test_event".
`
our uploader function logs that we deleted a message containing this test event ID, which is something we do after we've received a success message back from RS
`Message 7a64380a-8008-4972-ae06-b7adfe170cfe deleted with request id cdfb9c58-2003-0026-1b31-ea0427000000 and has TestEvent id 1af32e23-1c6b-4be2-aa67-d04dba36c1c5`
I can't find the test event in Metabase, so it seems we created one, sent the result to RS, but possibly failed to properly persist it
I can't find any further information about how the test event was generated unfortunately, but it happened with at least 7 other test events. we only get the error if the "ghost" test event has an error that triggers a warning from RS, so it's difficult to quantify how often this happens

**Comment by emmastephenson** [comment]
@mehansen I'm not sure that these events even get sent to the ReportStream uploader in the first place 😬 I believe they would fail at an earlier level, when we try to serialize the events before adding them to our queue for processing: https://github.com/CDCgov/prime-simplereport/blob/a476ef8221e6077e026b8628e309fcc245960770/backend/src/main/java/gov/cdc/usds/simplereport/api/model/TestEventExport.java#L411-L411

I checked our logs earlier today, and there were indeed a couple cases of this failure to serialize (made a ticket so we start getting alerted about those: https://github.com/CDCgov/prime-simplereport/issues/4643). So I think these test events with missing Result entities wouldn't even make it onto the queue for processing.
