### ISSUE TITLE
Upgrade static site Ruby version

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4859]
### Background
The Ruby version on the static site is fairly out of date and should be updated. Our current version (2.7) will be EOL by March 2023.

### Action Requested
Upgrade our Ruby version.

### Acceptance criteria
Ruby is upgraded on the static site and we're no longer facing the March EOL deadline.

**Comment by emmastephenson** [comment]
@emyl3 can you add any details to the description above? Want to make sure I captured what we talked about in standup yesterday

**Comment by emyl3** [comment]
@emmastephenson @rin-skylight 
My inclination is to upgrade to ruby 3.1.3 since 3.1 has been out for a year now and support will be until March 2025.
I am a little hesitant to upgrade to the latest (ruby 3.2.0) since it was released around 2 weeks ago. (see https://endoflife.date/ruby)
Do either of you see any issues with this? 🤔

**Comment by emmastephenson** [comment]
@emyl3 no issues on my end! Upgrading to 3.1 sounds like the safest course of action 👍
