### ISSUE TITLE
Schema changes for test result corrections

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#489]
- [x] backdate cleanup: https://github.com/CDCgov/prime-simplereport/issues/437
- [x] Migrate `test_order.test_event_id` to `test_event.test_order_id`
- [x] Add string column `test_event.reason_for_correction` defaults to `null`
- [x] Add enum `test_event.result_status` `original | corrected | removed`

schema work for https://github.com/CDCgov/prime-simplereport/issues/332 and https://github.com/CDCgov/prime-simplereport/issues/473

**Comment by benwarfield-usds** [comment]
A note for people to recall on this story, so it's not just in my head!

There is a scenario that I can see showing up here and at least one other place: entity A (here, TestOrder) has a one to many relationship with B (here, TestEvent), but has a common need to fetch a list of tuples of the type (A, most_recent(B)). This is something that standard SQL (and JPQL) do not support at all well, _but_ since it's a super common need, postgresql has a trick for it:

```sql
    SELECT DISTINCT ON (B.a_id) *
    FROM B
    ORDER BY B.a_id, created_at DESC
```

**Comment by TomNUSDS** [comment]
Schema work and backend work done. Still need frontend work related to showing/unarchiving patients. #612
