### ISSUE TITLE
Fix Metabase configuration and startup

### ISSUE THREAD

**Issue by alismx** [CDCgov/prime-simplereport#4951]
We want to automatically configure Metabase when we `terraform apply`

**Comment by rin-skylight** [comment]
Unfortunately, due to the limitations imposed by the variant of Metabase we use, applying these automatic configurations is not technically feasible. These are traditionally accomplished through means of a configuration file, but Metabase has blocked usage of that functionality without a paid plan. We could theoretically switch to a wrapped version of the Metabase image, but doing so runs the risk of introducing security vulnerabilities and data compromises.

This item can be revisited if the limitation changes in the future.
