### ISSUE TITLE
SPIKE: Self-Service for Support Team - Automatic Password Reset w/Reactivation

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#5722]
### Background / Description
When Support Staff is tasked with reactivating a user's account, they often will also have to reset that user's password at the same time. This is not true 100% of the time – the user may not always require a password reset.

### Requirements
Investigate the steps required to implement a self-service tool for the Support Team that can be used to reactivate a user (includes password reset).

### Acceptance Criteria / Definition of Done
Know of any corner cases or gotchas to think about (e.g. user is deleted)
Update ticket for adding password reset to existing user reactivation in admin page if necessary
Create tickets for adding reactivation + pw reset self-service tool to support page

Questions to address:
What's the user experience like when we include a password reset in the user reactivation mutation?
What's the difference between suspended and deactivated and how does that impact what we want the self-service tool to do?

**Comment by mehansen** [comment]
Need to followup with support to understand their flow - why do they need to do this instead of org admin?

**Comment by fzhao99** [comment]
## Problem Summary
To summarize the ask with screenshots (because I was a bit confused initially): 

Due to security regulations, we suspend user accounts after 60 days (context in [this PR](https://github.com/CDCgov/prime-simplereport/issues/1340)). At that point, this UI shows up on the admin page
<img width="1170" alt="Screenshot 2023-07-07 at 9 30 02 AM" src="https://github.com/CDCgov/prime-simplereport/assets/29645040/c9f16581-7472-4079-98e9-de5f392b1118">

Clicking activate user brings up this modal. 
<img width="638" alt="Screenshot 2023-07-07 at 9 33 04 AM" src="https://github.com/CDCgov/prime-simplereport/assets/29645040/8bb7f0f4-b74a-4d95-ae9d-f9bfb15f7efc">

The issue is that when reactivating, support often needs to also send a followup “reset password” email because folks have forgotten their passwords and therefore wanted a way to do both at one time.

## Recommendation
What we can probably do is add a third button on the modal with something along the lines of “activate with password reset” using the primary / secondary / cancel button layout like we have in other screens. Since support mentioned that ~60% of the requests also have a reset password option, we can probably make the button that does both the primary one and the reactivation only button secondary (if not remove the reactivation only one entirely)
<img width="641" alt="Screenshot 2023-07-07 at 9 34 11 AM" src="https://github.com/CDCgov/prime-simplereport/assets/29645040/38ccb9af-6e30-42ac-8b6e-b096b28a68e7">

That new button can probably just call a backend function that composes the reactivate user and resend password actions together. We'll need to add a new GQL mutation / do the appropriate GQL deployment dance to get things out correctly

## Tickets
- Add backend resolution / mutation code needed to auto send password 
- Adjust frontend modal to access new mutation
