### ISSUE TITLE
[BUG] Touchpoints form submissions not working

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#5783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Touchpoints modal on static site fails to submit

<img width="707" alt="Screenshot 2023-05-11 at 10 27 04" src="https://github.com/CDCgov/prime-simplereport/assets/20211771/4dd3102f-aa14-418b-8e5d-515057503eb0">

<img width="1123" alt="Screenshot 2023-05-11 at 10 39 31" src="https://github.com/CDCgov/prime-simplereport/assets/20211771/6ece0cc7-1af4-43ce-b08b-5547e8c087b9">

### Steps To Reproduce

- Go to SimpleReport static site (prod)
- Open the touchpoints modal (Click "How can we improve SimpleReport?")
- Fill out form (make sure you write "TESTING" or something similar in the comment so the team knows this is not real feedback)
- Click "Submit"
- Form does not submit and errors out

### Expected Behavior

Form should submit with no issues

### Additional context

Last successful message recorded in touchpoints for static site was on February 10, 2023, when testing the Node upgrade

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by mehansen** [comment]
in the touchpoint configuration panel, you may have to authorize where they're getting responses from - this could be the issue

to access touchpoints config panel - need a login.gov account

**Comment by johanna-skylight** [comment]
Root cause was that the url set for the form was https://simplereport.gov but the origin of the request was https://**www**.simplereport.gov

I have set both urls for the form in case the version without the www was updated because of a previous bug fix. I updated the urls for the app form as well so it accepts both versions.



![Image](https://github.com/CDCgov/prime-simplereport/assets/103958711/a9790e4e-8a3e-4449-b7df-bead75475df8)
