### ISSUE TITLE
SPIKE: Investigate corner cases around deleting facilities

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#5977]
### Background / Description
Before we expose the ability to delete facilities to support in #5847, let's look into some corner cases that could occur when a facility is deleted. These states are already possible because we do delete facilities for support as part of their escalation/support request process so these are essentially existing corner cases that could cause bugs. Let's tighten this up before we expose this as a self-service functionality that we have less visibility over.

### Requirements
Understand the current behavior of SR after facility deletion in the following cases:
* what happens to pxp flow if patient viewing a result performed at a facility that has since been deleted?
* what happens to patient assigned to a facility that gets deleted - what do we see in Edit Patient and can we conduct a test for them from anywhere?
  * should we warn support before deleting a facility if there are patients only assigned to that facility because they will potentially become untestable?
* does deleting a facility impact the result view table? what does the Testing facility column say? does the Testing facility filter dropdown include deleted facilities?
* what happens if a user logs in and they have access to no facilities?

Propose solution(s) to preventing us from getting into any bad states when deleting a facility.
Options that might address some of the issues:
* prevent deletion if any users are assigned to that facility
* ask support to check a box confirming they'd like to transfer any users assigned to that facility to have all facility access, or give a dropdown to select a facility for them to transfer access to

### Acceptance Criteria / Definition of Done
Answer the above questions and have a team discussion on proposed solutions
Any necessary followup tickets are created or #5847 is updated with additional detail

**Comment by emyl3** [comment]
**Findings** (IN PROGRESS)
1. What happens to pxp flow if patient viewing a result performed at a facility that has since been deleted?
  - Patient who had test performed at a deleted facility can continue to access their results via the pxp flow as long as the link is not expired

2. What happens to patient assigned to a facility that gets deleted - what do we see in Edit Patient and can we conduct a test for them from anywhere?

3. Should we warn support before deleting a facility if there are patients only assigned to that facility because they will potentially become untestable?

4. Does deleting a facility impact the result view table? What does the Testing facility column say? Does the Testing facility filter dropdown include deleted facilities?
  - deleting a facility does not impact the result table view
  - the "Testing facility column" shows the deleted facility name as expected
  - the "Testing facility dropdown" includes the deleted facility

5. what happens if a user logs in and they have access to no facilities?

**Comment by emyl3** [comment]
group comments:
- do not allow deleting of facility if patient is in the testing queue (show messaging)

confirmation modal on facility deletion:
- display number of patients (affected by facility deletion) before deleting a facility (only assigned to that facility)
- show warning of # of users that would be affected by facility deletion before deleting a facility (only assigned to that facility)

note: only org admins can see results in a deleted facility
- prevent admin from correcting a test result in a deleted facility (please reach out to support msg here)

**Comment by emyl3** [comment]
To address this "prevent admin from correcting a test result in a deleted facility (please reach out to support msg here)"
https://github.com/CDCgov/prime-simplereport/issues/6115
