### ISSUE TITLE
Create designs for QR code and magic link experience

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#617]
Create the designs that display a QR code and magic link

**Comment by katiealoisi** [comment]
@maya Designs are ready in [figma](https://www.figma.com/proto/VGBQmqKMTjO1tdYTCpzwcd/Design-WIP?node-id=312%3A74&scaling=scale-down). Search for a person and hit "Begin Test" to see the expected interaction. Let us know if you have any questions or suggestions.

The team will also need to think through the security implications of using QR codes in this way, especially once we have results in the patient view. What are the security considerations here and what do we need to ask/what do we need to do/who do we need to talk to in order to address them? If the appropriate people on your team can start thinking through these questions, that would be great!

**Comment by hmyers-cms** [comment]
On the security point, my specific concern is that there is nothing stopping the test administrator from scanning that code on their own phone and entering the DoB, which they have right in front of them. With that they could see all past test results for that person even if their own permissions prevented them from seeing that info in SimpleReport

**Comment by maya** [comment]
Thank you, will take a look at the designs. Those are good questions and will refer the security questions to our team, thanks!

**Comment by maya** [comment]
this is done, thanks!
