### ISSUE TITLE
Record test type on device type

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#631]
**As an administrator, I need to be able to set the full test name and test category that is conducted on a type of device, so that users can see those details about the tests that were performed on them without looking things up on the internet.**

(Shimmed currently for the test types that our current devices perform.)

Proposed permanent implementation:
* create a TestDescription entity that contains the names (see discussion below and in #426) and the type (PCR, Antigen, Antibody) of a test
* link to this, for now, from DeviceType, in place of the current opaque LOINC code string field.
* admin console ability to edit test descriptions
* admin console ability to link devices to test descriptions

This would allow printing to be seamless for new device types, and also make pre-population of people's past test types more accurate.

For a more flexible implementation, we may in the future need 
* a many-to-many relationship with DeviceType instead of many-to-one
* a separate "Condition" (or "Disease" if you're blunt) entity or enumeration that allows us to in some way use this application for both Flu and COVID-19 tests.

**Comment by dmethvin-gov** [comment]
There are some related issues with Hub reporting, see TestEventExport.Java at the bottom. Our current assumption there probably holds for rapid PCR tests though.

**Comment by benwarfield-usds** [comment]
I think this needs some specificity about 
* what "test type" means
* what its relationship is to the device type
* what its relationship is to the possible future directions of the application.

Other than that I can totally just drop this into the swab-types work! 😁

**Comment by benwarfield-usds** [comment]
So, having done some pulling on threads with help from the Hub team, I can report that we do in fact record and send this, because that is what the LOINC code on each device is for. (Charitably, this is not well-documented—uncharitably, the engineers didn't understand that fact when we were throwing together the DB schema.)  All of our tests are one of the following:

* [94534-5 — SARS-CoV-2 (COVID-19) RdRp gene [Presence] in Respiratory specimen by NAA with probe detection](https://loinc.org/94534-5/)
* [95209-3 — SARS-CoV+SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay](https://loinc.org/95209-3/)
* [94558-4 — SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay](https://loinc.org/94558-4/)

We report the LOINC code to the hub, and they look up the human-readable value.

For purposes of the original discussion, we should probably have some logic of our own about which LOINC codes correspond to antigen tests and which to PCR tests: I am not sure if that falls within the intended scope of this ticket or not.

**Comment by dmethvin-gov** [comment]
The need (at least for my ticket on printing) was that we had to show the human-readable description. I suppose there are a bunch of options here including the original ideal of putting the description in the device record. Alternatively the frontend can take the LOINC code and look up its own description wired into some table. Although that is probably the approach we'll take right now in order to unblock things, the downside is what to do when there is a new device and/or LOINC code and we get all the way to deploying the device in the field without a description to be printed.

**Comment by benwarfield-usds** [comment]
Based on @dmethvin-gov's clarification, the following is proposed:

1. we will add test name to the API immediately, to unblock test result printing, using a horrifying hard-coded shim based on the current LIVD table
2. we will subsequently make a free-standing database object that contains this information, so that adding a new test type will not require a code change

Agreed-upon schema change for the front end:

```graphqls
type TestDescription {
    name: String!
    loincCode: String!
}
type TestResult {
    ...
    testPerformed: TestDescription!
}
```
(it should probably go into TestOrder as well, come right down to it, but we don't _need_ it there...)
