### ISSUE TITLE
[BUG] Don't fetch support admin user on empty "Manage users" page

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#6412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. Log in as a user with support admin privileges
2. Find an org that your support admin user is not a part of with only one user account
3. Delete that one remaining user in that org
4. Ghost into that org that now has no users
5. Open your dev tools and "Network" tab
6. Notice that a `GetUser` request is being made to fetch your support admin account

### Steps To Reproduce

See above

### Expected Behavior

We should not be fetching the logged in user (e.g. support admin user) if that user is not part of the organization.

### Additional context

This behavior is caused by [this line](https://github.com/CDCgov/prime-simplereport/blob/ab40690b0825e7ea4d776e25cb1dee632e83c66d/frontend/src/app/Settings/Users/ManageUsers.tsx#L125). We default to getting the logged in user when there is no active user selected.

[See this comment in the PR](https://github.com/CDCgov/prime-simplereport/pull/6394#pullrequestreview-1594130371).

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by mehansen** [comment]
![Image](https://github.com/CDCgov/prime-simplereport/assets/6401323/f35503f9-15b1-4c51-8c08-5126ec63cf70)


See if above screenshot is related. If it's caused by Okta group still existing when org is not in the table (even if isDeleted = true) then I wouldn't worry too much about it

Look into why we are falling back to using the logged in user ID for getUser if there's no active user
