### ISSUE TITLE
Throw UNSUPPORTED page on IE

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#664]
As a user trying to access SimpleReport on Internet Explorer (not edge) I want to know that I need to change my browser to Chrome so that I can use the application, since it's totally broken in IE.

- [x] @katiealoisi @hmyers-cms - Something to work on when you have time. We should tell users when they are in an unsupported browser, right not it just fails.

Updated design in [**Engineering prototype**.](https://www.figma.com/file/VGBQmqKMTjO1tdYTCpzwcd/Design-WIP?node-id=3415%3A36512)

**Comment by katiealoisi** [comment]
What browsers and versions do we support? We can let them know they are using a web browser we do not support + list the browsers we recommend for the best experience. Something like this: 

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/4efc3a40-bc70-4a6a-ac3b-501a59397905)

**Comment by katiealoisi** [comment]
Tagging @timothybest-usds to see if you know the answer to my Q above: What browsers and versions do we support?

**Comment by timothybest-usds** [comment]
We aren't in a place to guarantee support for browser versions.  I would have the page recommend the user upgrades to the latest version of Chrome or Safari (We currently do not support Firefox due to  a bug https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/432)

**Comment by nickscialli-usds** [comment]
After some discussion based on a recent occurrence of a user trying to use IE, it seems like the best approach here is to allow IE users to browse the static site but, when clicking the "log in" link, route any IE users to the aforementioned "Browser not supported page." There are some relatively easy ways to detect the client's browser type (e.g., https://stackoverflow.com/a/61979493)

**Comment by emmastephenson** [comment]
@nickscialli-usds  Should we also block Firefox users attempting to log in? I know it's not a supported browser, but I'm not sure if we want to block usage altogether.

**Comment by nickscialli-usds** [comment]
@emmastephenson I guess this issue is that, if a FF user logs in, is it okay that they hit this bug: https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/432

And that's more of a product question.

I'd personally want to squash the bug and then not have to worry about blocking FF users.

**Comment by maya** [comment]
@aliciabeckett-gov thoughts on FF?

**Comment by aliciabeckett-gov** [comment]
I do not want to block FF users. Agree with Nick we should allow them to log in and fix that bug if needed.

**Comment by emmastephenson** [comment]
Sounds good. For now, we're only showing the unsupported browser message to IE users, and recommending Chrome and Safari as alternatives. Firefox users will be able to log in, but we won't show it as a recommended browser yet.
