### ISSUE TITLE
Move Patient Search to the Backend for Test Queue

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#740]
Currently the test queue grabs a list of all people and the search is implemented locally. By implementing a backend search will have two benefits:
- More secure access control restrictions for entry only users
- Reduced page load time

Backend:
- [x] Create a new graphql mutation `patientSearch(facilityID: String!, query: String!): [Patient]`
- [x] Query should grab the first ten rows that partial match with the `person.first_name` or `person.last_name` and restricted by current facility and not deleted
```
SELECT ...
FROM person
WHERE  first_name LIKE 'query%' OR last_name LIKE 'query%'
LIMIT 10;
```
- [x] patient search should return a error if `query.length() < 3`
- [x] restrict patient search to the `RequirePermissionSearchPatients` permissions
- [x] update permissions on `getPatients()` from `RequirePermissionSearchPatients` to  `RequirePermissionReadPatientList` 

Frontend:

- [x] remove query to get all patients
- [x] rewired search to call  `patientSearch` when a user adds 3 or more characters to the search box
- [x] there should be a `200ms` debounce delay between when the user stops typing and the call to `patientSearch` is made https://stackoverflow.com/questions/53071774/reactjs-delay-onchange-while-typing

**Comment by TomNUSDS** [comment]
@benwarfield-usds @jeremyzitomer-usds 

This item is presenting some issues: 
> restrict patient search to the RequirePermissionSearchPatients permissions

Because the permissions model is declarative (each call has an `@AuthorizationConfiguration.`) it means there's an spread of permission calls and no way to combine permissions. It's better explained by example.

The current permissions related to PatientLists
 - `RequirePermissionReadResultList` (see list of patients)
 - `RequirePermissionReadArchivedPatientList` (see list of isDeleted patients)
 - `RequirePermissionSearchPatients` (search list of patients) *new*

Also, to complicate things, the `getPatients()` graphql call (aka `Query.patients(...):: [Patient]`) allows a null `facilityId` to mean "query across all facilities".

So, to check permissions, the single call from the graphql client must spread out to multiple calls internally to check permissions. `ReadResultList` || `ReadArchivedPatientList` x  `facilityId=null` || `facilityId!=null` results in 4 such calls.

If we add another permission `SearchPatients`, from the graphql api level, it's just another optional parameter, but once it hits java, we now have to spread out to even MORE permissions-verifying calls. 

Also, I'm not 100% certain how we inforce multiple permissions like searching *and* isDeleted patients access.

It becomes a lot easier if there is a runtime alternative to checking permissions.
