### ISSUE TITLE
Create reporting dashboard for LAC

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7548]
LAC is interested in getting regular emails detailing the number of HIV results we're sending. They want something detailing the number of results submitted during a certain time frame for each disease (for now just HIV, but should show other diseases once we're supporting those).

To be discussed during refinement:
- parameters around the query:
  - patient from LAC, facility in LAC, disease is STI disease... anything else?
  - since not all our addresses have county, what cities should we filter by?
- they might also like a list of facilities sending HIV results to them

**Comment by emyl3** [comment]
Filtered by cities in this list:
https://en.wikipedia.org/wiki/List_of_cities_in_Los_Angeles_County,_California

**Comment by emyl3** [comment]
For filtering by patients just doing the county since we don't expose cities or zip codes in metabase

**Comment by emyl3** [comment]
LAC gets results for ordering provider zip codes in LAC

Maybe show zip codes represented in dashboard? (if using cities above as the filter)

**Comment by emyl3** [comment]
LAC do not receive test data from patients who have LAC addresses -- they only care about ordering provider zip code

**Comment by emyl3** [comment]
Ready for review: https://www.simplereport.gov/metabase/dashboard/265-los-angeles-county-lac-hiv-dashboard

**Decisions**
- Filtering
   -  by ordering provider city names that are included in this list: https://en.wikipedia.org/wiki/List_of_cities_in_Los_Angeles_County,_California
   - filter by ordering provider state is CA
- Dashboard
  - count of all HIV results reported (all-time)
  - zip codes of ordering providers reporting HIV results (this is because we are filtering by city and not by zip code. We want to make sure they can flag if any zip codes not in LAC are being counted in this dashboard)
  - facilities name + CLIAs that are reporting HIV

**Comment by emyl3** [comment]
@DanielSass shared that LAC only cares about ordering provider zip codes for HIV... When we introduce other STIs, LAC will also want results for patient address/county/state NOT ordering provider zip. So this dashboard will need to be updated once other STIs are introduced.

**Comment by emyl3** [comment]
This has been approved by devs: https://www.simplereport.gov/metabase/dashboard/265-los-angeles-county-lac-hiv-dashboard

We just need to add email recipients once results are being submitted and let recipients know that they will be receiving this. This will be done later!

cc @jayna-SkylightDigital
