### ISSUE TITLE
Update Bulk Result File Validation: Result Code

### ISSUE THREAD

**Issue by DanielSass** [CDCgov/prime-simplereport#7898]
File validation for the bulk result uploader was a contributing factor to the bug described in #7897.

Requested update:

Adjust the validation for the `test_result` field in the bulk uploader to be more stringent.

[/backend/src/main/java/gov/cdc/usds/simplereport/validators/CsvValidatorUtils.java#L273-L275](https://github.com/CDCgov/prime-simplereport/blob/268ddb50c86572fc83419243cc36a45dfd4845a1/backend/src/main/java/gov/cdc/usds/simplereport/validators/CsvValidatorUtils.java#L273-L275)
```java
  public static List<FeedbackMessage> validateTestResult(ValueOrError input) {
    return validateSpecificValueOrSNOMED(input, TEST_RESULT_VALUES);
  }
```

Rather than allowing anything that looks like a snomed (i.e. the regex currently in place), we should validate against a list of specific snomeds that we support and can effectively map in the fhir converter (which should include any snomeds in the [covid](https://prime.cdc.gov/api/metadata/livd) or [hiv](https://prime.cdc.gov/api/metadata/livd) livd tables).

The SNOMEDs we allow should be the same ones being explicitly mapped to normal/abnormal flags in #7897

**Comment by emyl3** [comment]
Since deploying #7897, I'm checking what folks have submitted as codes that we don't support using the following query:
```
traces 
| where message has "Unsupported SNOMED result code:" 
| parse message with * "Unsupported SNOMED result code: " SNOMEDCodeEntered
| extend SNOMED = split(SNOMEDCodeEntered, ":")
| mv-expand SNOMED to typeof(string)
| summarize occurrences=count() by SNOMED
```
https://portal.azure.com/#@cdc.onmicrosoft.com/resource/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourceGroups/prime-simple-report-prod/providers/Microsoft.Insights/components/prime-simple-report-prod-insights/logs

And I'm seeing, these results


![Image](https://github.com/user-attachments/assets/dba22dfa-edc8-4426-9188-194930836d94)
