### ISSUE TITLE
V1 Only let users save facility addresses in supported states

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#915]
If a user tries to save an address in a state where we are not live, they should not be able to save and should see an error message.

Design options:
-Limit dropdown to states where we are live
-Show the user an error message on save
@katiealoisi & Heather can we get a design for this?

**Comment by hmyers-cms** [comment]
We decided to show the full list of states, but provide an error as soon as a user selects a non-supported state (rather than after clicking save).

We did not want to limit the list of states because it would not be clear to users why the other states or not listed.

![New Facility.png](https://images.zenhubusercontent.com/600201c5b437d97abbef2e2f/d2a46a4b-a814-410f-ab2f-56f8df363efc)

**Comment by aliciabeckett-gov** [comment]
Looks good! Where is the link for what states are supported going to be?

I worry about direct linking to resources in the UI because it's easy for them to get out of sync and break :(

**Comment by katiealoisi** [comment]
The link goes to the resources page - specifically here: https://cdcgov.github.io/SimpleReport_Public_Site/resources/using-simplereport/manage-facility-info/find-supported-jurisdictions/ 

What are you concerned about getting out of sync?

**Comment by aliciabeckett-gov** [comment]
If we change the link it will break the app, and sometimes that's not obvious.

**Comment by aliciabeckett-gov** [comment]
I have this concern in general in linking directly to documentation. So I think it's a bigger thing on do we do direct links, or just generally say go to simplereport.gov/resources

**Comment by hmyers-cms** [comment]
We can just be sure to set up redirects if we change URLs

**Comment by katiealoisi** [comment]
Yeah I don't think directing them to simplereport.gov/resources will be
helpful since they'd have to wade through that page to find the section on
supported jurisdictions. Are you okay with Heather's suggestion to set up
redirects instead?

**Comment by aliciabeckett-gov** [comment]
I think this is going to end up being painful for us, but I’m willing to go with it for now.

Redirects are also work, so if  this ends up being more than a small effort I’ll want to remove the links at that point.

**Comment by maya** [comment]
Some feedback on the [proposed design](https://github.com/CDCgov/prime-simplereport/issues/915#issuecomment-786754705):
I'm assuming this is an auto-error rather than an error when submitting the form. Is that assumption accurate?

It's not accessible to put this alert box after the alert bc you want to give the person a chance to correct it. And specifically in that location, it skips the subsequent form field too.

If the error is on submit, the alert should go at the top of the form. If it's an auto-error, it should use an inline error. When this is single column #1231, there'll be space to add more text.

/cc @vz3 

Also, I did not see figma link or would share feedback in there.

**Comment by katiealoisi** [comment]
Yes, this is an auto-error. We don't want the user to fill out the entire form only to realize they can't proceed.

It sounds like the way to proceed is to first make the facility form single column (#1231) then move it to an inline error.

**Comment by maya** [comment]
FYI the single-column form was merged, not sure if you're still working on this @nathancrtr? 

tagging @Rebecca-LM for content review of the error message.

**Comment by Rebecca-LM** [comment]
@maya I would change "is not currently..." to "isn't currently..." (The aim is to get language towards writing like we speak/plain language.) Also add a period after the word "supported" in the line below (but do not hyperlink the period).
